cat > /root/net-tune-menu.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SYSCTL_FILE="/etc/sysctl.d/99-net-tune-menu.conf"
BACKUP_DIR="/root/sysctl-backups"
mkdir -p "$BACKUP_DIR"

CURRENT_PROFILE=""

# ---------- 基础函数 ----------
ts() { date +%F_%H%M%S; }

backup_now() {
  local t
  t="$(ts)"
  sysctl -a 2>/dev/null > "${BACKUP_DIR}/sysctl-all-${t}.bak" || true
  [[ -f "$SYSCTL_FILE" ]] && cp -a "$SYSCTL_FILE" "${BACKUP_DIR}/99-net-tune-menu.conf.${t}.bak"
}

reload_sysctl() {
  sysctl --system >/dev/null
}

print_key_params() {
  echo
  echo "=== 当前关键参数 ==="
  sysctl \
    net.core.netdev_max_backlog \
    net.core.somaxconn \
    net.ipv4.tcp_max_syn_backlog \
    net.core.rmem_default \
    net.core.wmem_default \
    net.core.rmem_max \
    net.core.wmem_max \
    net.ipv4.tcp_rmem \
    net.ipv4.tcp_wmem \
    net.ipv4.udp_rmem_min \
    net.ipv4.udp_wmem_min \
    net.ipv4.tcp_fastopen \
    net.ipv4.tcp_mtu_probing \
    net.ipv4.tcp_fin_timeout \
    net.ipv4.tcp_tw_reuse \
    net.ipv4.ip_local_port_range \
    net.ipv4.tcp_syncookies \
    net.core.default_qdisc \
    net.ipv4.tcp_congestion_control \
    net.ipv4.tcp_slow_start_after_idle 2>/dev/null || true
  echo
}

show_current_config_file() {
  echo "=== 当前配置文件: $SYSCTL_FILE ==="
  if [[ -f "$SYSCTL_FILE" ]]; then
    cat "$SYSCTL_FILE"
  else
    echo "未找到配置文件（尚未应用菜单配置）"
  fi
  echo
}

# ---------- 公共基础项 ----------
common_base() {
  cat <<'CONF'
# ===== Generated by net-tune-menu.sh =====
# 通用基础项
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 20
net.ipv4.ip_local_port_range = 10240 65535
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_slow_start_after_idle = 0
CONF
}

# ---------- 配置模板 ----------
profile_balanced() {
  cat <<'CONF'
# ---- profile: balanced ----
net.core.netdev_max_backlog = 65536
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}

profile_aggressive() {
  cat <<'CONF'
# ---- profile: aggressive ----
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_fin_timeout = 15
CONF
}

profile_aggressive_safe() {
  cat <<'CONF'
# ---- profile: aggressive_safe ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}

profile_xray_hy2() {
  cat <<'CONF'
# ---- profile: xray_hy2 ----
# 针对 TCP + UDP 混合代理
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}

profile_low_1c1g() {
  cat <<'CONF'
# ---- profile: low_1c1g ----
net.core.netdev_max_backlog = 8192
net.core.somaxconn = 2048
net.ipv4.tcp_max_syn_backlog = 8192
net.core.rmem_default = 131072
net.core.wmem_default = 131072
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65536 8388608
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}

profile_low_2c2g() {
  cat <<'CONF'
# ---- profile: low_2c2g ----
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 16384
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}

profile_bw_1g() {
  cat <<'CONF'
# ---- profile: bw_1g ----
net.core.netdev_max_backlog = 32768
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}

profile_bw_10g() {
  cat <<'CONF'
# ---- profile: bw_10g ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}

emit_profile() {
  case "$1" in
    balanced)        profile_balanced ;;
    aggressive)      profile_aggressive ;;
    aggressive_safe) profile_aggressive_safe ;;
    xray_hy2)        profile_xray_hy2 ;;
    low_1c1g)        profile_low_1c1g ;;
    low_2c2g)        profile_low_2c2g ;;
    bw_1g)           profile_bw_1g ;;
    bw_10g)          profile_bw_10g ;;
    *)
      echo "未知 profile: $1" >&2
      return 1
      ;;
  esac
}

apply_profile() {
  local p="$1"
  backup_now
  {
    common_base
    emit_profile "$p"
  } > "$SYSCTL_FILE"

  reload_sysctl
  CURRENT_PROFILE="$p"
  echo
  echo "✅ 已应用配置: $p"
  echo "📄 配置文件: $SYSCTL_FILE"
  echo "💾 备份目录: $BACKUP_DIR"
  print_key_params
}

preview_profile() {
  local p="$1"
  echo "===== 预览 profile: $p ====="
  common_base
  emit_profile "$p"
  echo
}

rollback_config() {
  if [[ -f "$SYSCTL_FILE" ]]; then
    rm -f "$SYSCTL_FILE"
    reload_sysctl
    echo "✅ 已回滚（删除 $SYSCTL_FILE 并重载 sysctl）"
  else
    echo "ℹ️ 未发现 $SYSCTL_FILE，无需回滚"
  fi
}

watch_metrics() {
  echo "进入实时监控（每2秒刷新），Ctrl+C 返回菜单..."
  sleep 1
  while true; do
    clear
    echo "===== $(date '+%F %T') ====="
    echo "[softnet_stat 丢包列(第2列) 前8行]"
    awk '{print NR ": " $2}' /proc/net/softnet_stat | head -n 8
    echo
    echo "[ss -s]"
    ss -s || true
    echo
    echo "[netstat关键统计]"
    netstat -s 2>/dev/null | grep -Ei 'listen|overflow|drop|retrans|fail|prune' | head -n 40 || true
    echo
    echo "[内存]"
    free -h || true
    sleep 2
  done
}

auto_recommend() {
  local mem_mb cpu nic speed
  mem_mb=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
  cpu=$(nproc)
  nic=$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')
  speed=0
  if [[ -n "${nic:-}" && -r "/sys/class/net/$nic/speed" ]]; then
    speed=$(cat "/sys/class/net/$nic/speed" 2>/dev/null || echo 0)
  fi

  local rec="balanced"
  if (( cpu <= 1 || mem_mb <= 1200 )); then
    rec="low_1c1g"
  elif (( cpu <= 2 || mem_mb <= 2400 )); then
    rec="low_2c2g"
  elif (( speed >= 10000 )); then
    rec="bw_10g"
  elif (( speed >= 1000 )); then
    rec="bw_1g"
  fi

  echo
  echo "=== 自动识别结果 ==="
  echo "CPU核数: $cpu"
  echo "内存MB: $mem_mb"
  echo "默认网卡: ${nic:-unknown}"
  echo "网卡速率(Mbps): ${speed:-unknown}"
  echo "推荐配置: $rec"
  echo
  read -rp "是否立即应用推荐配置? [y/N]: " yn
  case "${yn:-N}" in
    y|Y) apply_profile "$rec" ;;
    *) echo "已取消应用。" ;;
  esac
}

choose_profile_menu() {
  while true; do
    echo
    echo "请选择要应用的配置："
    echo " 1) balanced        (平衡版)"
    echo " 2) aggressive      (激进版)"
    echo " 3) aggressive_safe (激进但更稳)"
    echo " 4) xray_hy2        (Xray/Hy2 专项)"
    echo " 5) low_1c1g        (低内存保守 1C/1G)"
    echo " 6) low_2c2g        (低内存保守 2C/2G)"
    echo " 7) bw_1g           (高带宽 1G口)"
    echo " 8) bw_10g          (高带宽 10G口)"
    echo " 9) 返回上级菜单"
    read -rp "输入选项 [1-9]: " c

    case "$c" in
      1) apply_profile balanced; break ;;
      2) apply_profile aggressive; break ;;
      3) apply_profile aggressive_safe; break ;;
      4) apply_profile xray_hy2; break ;;
      5) apply_profile low_1c1g; break ;;
      6) apply_profile low_2c2g; break ;;
      7) apply_profile bw_1g; break ;;
      8) apply_profile bw_10g; break ;;
      9) break ;;
      *) echo "无效输入，请重试。" ;;
    esac
  done
}

preview_menu() {
  while true; do
    echo
    echo "请选择要预览的配置："
    echo " 1) balanced"
    echo " 2) aggressive"
    echo " 3) aggressive_safe"
    echo " 4) xray_hy2"
    echo " 5) low_1c1g"
    echo " 6) low_2c2g"
    echo " 7) bw_1g"
    echo " 8) bw_10g"
    echo " 9) 返回上级菜单"
    read -rp "输入选项 [1-9]: " c

    case "$c" in
      1) preview_profile balanced ;;
      2) preview_profile aggressive ;;
      3) preview_profile aggressive_safe ;;
      4) preview_profile xray_hy2 ;;
      5) preview_profile low_1c1g ;;
      6) preview_profile low_2c2g ;;
      7) preview_profile bw_1g ;;
      8) preview_profile bw_10g ;;
      9) break ;;
      *) echo "无效输入，请重试。" ;;
    esac
  done
}

main_menu() {
  while true; do
    echo
    echo "=================================================="
    echo " Linux 网络优化交互菜单 (Xray/Hy2/通用)"
    echo " 配置文件: $SYSCTL_FILE"
    echo " 当前会话已应用: ${CURRENT_PROFILE:-无}"
    echo "=================================================="
    echo " 1) 应用配置（选择版本）"
    echo " 2) 预览配置（不应用）"
    echo " 3) 自动识别并推荐"
    echo " 4) 查看当前状态"
    echo " 5) 查看当前配置文件"
    echo " 6) 实时监控（watch）"
    echo " 7) 一键回滚"
    echo " 0) 退出"
    read -rp "请输入选项 [0-7]: " choice

    case "$choice" in
      1) choose_profile_menu ;;
      2) preview_menu ;;
      3) auto_recommend ;;
      4) print_key_params ;;
      5) show_current_config_file ;;
      6) watch_metrics ;;
      7) rollback_config ;;
      0) echo "已退出。"; exit 0 ;;
      *) echo "无效输入，请重试。" ;;
    esac
  done
}

# root 检查
if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "请用 root 运行：sudo bash /root/net-tune-menu.sh"
  exit 1
fi

main_menu
EOF

chmod +x /root/net-tune-menu.sh
bash /root/net-tune-menu.sh
