cat > /root/net-tune-pro-v3-zh.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# ===================== 基础路径 =====================
ACTIVE_FILE="/etc/sysctl.d/99-net-tune-pro-v3.conf"            # 网络方案托管文件
BBR_SYSCTL_FILE="/etc/sysctl.d/99-joeyblog.conf"               # BBR/QDISC托管文件
MODULES_CONF="/etc/modules-load.d/joeyblog-qdisc.conf"         # qdisc模块自动加载
BACKUP_DIR="/root/sysctl-backups-v3"
PERM_DIR="/root/sysctl-permanent-baseline-v3"
LAST_APPLY_DIR="${BACKUP_DIR}/last_apply"
HISTORY_DIR="${BACKUP_DIR}/history"
LOG_FILE="/var/log/net-tune-pro-v3.log"

mkdir -p "$BACKUP_DIR" "$PERM_DIR" "$LAST_APPLY_DIR" "$HISTORY_DIR"
touch "$LOG_FILE"

CURRENT_PROFILE=""
ARCH="$(uname -m)"

# 版本号
VERSION="3.1.0"

# ===================== 颜色 =====================
RED='\033[31m'; GREEN='\033[32m'; YELLOW='\033[33m'; BLUE='\033[36m'; BOLD='\033[1m'; NC='\033[0m'
ok(){ echo -e "${GREEN}✅ $*${NC}"; }
warn(){ echo -e "${YELLOW}⚠️  $*${NC}"; }
err(){ echo -e "${RED}❌ $*${NC}"; }
info(){ echo -e "${BLUE}ℹ️  $*${NC}"; }
line(){ echo "------------------------------------------------------------"; }

log(){ echo "[$(date '+%F %T')] $*" >> "$LOG_FILE"; }
pause(){ read -rp "按 Enter 继续..."; }
ts(){ date +%F_%H%M%S; }
cmd_exists(){ command -v "$1" >/dev/null 2>&1; }

need_root(){
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "请使用 root 运行：sudo bash /root/net-tune-pro-v3-zh.sh"
    exit 1
  fi
}

is_debian_like(){
  cmd_exists apt-get
}

# ===================== 依赖检查（尽量不强装） =====================
check_base_deps(){
  local miss=0
  for c in sysctl awk grep sed ip ss find mktemp install; do
    if ! cmd_exists "$c"; then
      err "缺少基础依赖：$c"
      miss=1
    fi
  done
  if (( miss == 1 )); then
    err "基础依赖不完整，请先安装后重试。"
    return 1
  fi
  return 0
}

ensure_bbr_deps_debian(){
  local required=("curl" "wget" "dpkg" "awk" "sed" "sysctl" "jq")
  local need_install=()
  for c in "${required[@]}"; do
    cmd_exists "$c" || need_install+=("$c")
  done

  if [[ ${#need_install[@]} -gt 0 ]]; then
    info "检测到缺少依赖：${need_install[*]}"
    apt-get update -y >/dev/null 2>&1 || true
    apt-get install -y "${need_install[@]}" >/dev/null 2>&1 || {
      err "依赖安装失败：${need_install[*]}"
      return 1
    }
    ok "依赖安装完成"
  fi
}

# ===================== 网络优化方案模板 =====================
common_base() {
cat <<'CONF'
# ===== Generated by net-tune-pro-v3-zh.sh =====
# 通用基础项
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 20
net.ipv4.ip_local_port_range = 10240 65535
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_slow_start_after_idle = 0
CONF
}
profile_balanced(){ cat <<'CONF'
# ---- 方案：平衡版 ----
net.core.netdev_max_backlog = 65536
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_aggressive(){ cat <<'CONF'
# ---- 方案：激进版 ----
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_fin_timeout = 15
CONF
}
profile_aggressive_safe(){ cat <<'CONF'
# ---- 方案：激进稳妥版 ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_udp_quic(){ cat <<'CONF'
# ---- 方案：UDP 专项（QUIC/UDP 优化） ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 524288
net.core.wmem_default = 524288
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 65536
net.ipv4.udp_wmem_min = 65536
net.core.netdev_budget = 600
net.core.netdev_budget_usecs = 20000
net.ipv4.udp_mem = 394110 524880 789222
net.ipv4.tcp_notsent_lowat = 16384
CONF
}
profile_low_1c1g(){ cat <<'CONF'
# ---- 方案：低内存保守版 1C/1G ----
net.core.netdev_max_backlog = 8192
net.core.somaxconn = 2048
net.ipv4.tcp_max_syn_backlog = 8192
net.core.rmem_default = 131072
net.core.wmem_default = 131072
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65536 8388608
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}
profile_low_2c2g(){ cat <<'CONF'
# ---- 方案：低内存保守版 2C/2G ----
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 16384
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}
profile_bw_1g(){ cat <<'CONF'
# ---- 方案：高带宽版 1G口 ----
net.core.netdev_max_backlog = 32768
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_bw_10g(){ cat <<'CONF'
# ---- 方案：高带宽版 10G口 ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_vps_max(){ cat <<'CONF'
# ---- 方案：VPS 极致带宽版（虚拟网卡） ----
# 针对虚拟化环境优化，最大化带宽利用率
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 524288
net.core.wmem_default = 524288
net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.ipv4.tcp_rmem = 4096 131072 134217728
net.ipv4.tcp_wmem = 4096 131072 134217728
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
CONF
}

profile_streaming(){ cat <<'CONF'
# ---- 方案：流媒体代理版（VLESS/Reality TCP 优化） ----
# 针对 Netflix/YouTube/TikTok 等视频流媒体场景
# 基于激进稳妥版缓冲区 + 流媒体专用 TCP 选项
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_thin_linear_timeouts = 1
CONF
}

emit_profile(){
  case "$1" in
    balanced) profile_balanced ;;
    aggressive) profile_aggressive ;;
    aggressive_safe) profile_aggressive_safe ;;
    udp_quic) profile_udp_quic ;;
    streaming) profile_streaming ;;
    low_1c1g) profile_low_1c1g ;;
    low_2c2g) profile_low_2c2g ;;
    bw_1g) profile_bw_1g ;;
    bw_10g) profile_bw_10g ;;
    vps_max) profile_vps_max ;;
    *) return 1 ;;
  esac
}

# ===================== 校验/检查 =====================
extract_max_from_triplet(){ awk '{print $3}' <<<"$1"; }
escape_regex() { sed -e 's/[][(){}.^$*+?|\/]/\\&/g' <<<"$1"; }

validate_profile_semantics(){
  local tmp="$1"
  local rmem_max wmem_max tcp_rmem tcp_wmem tr tw
  rmem_max="$(awk -F= '/^[[:space:]]*net\.core\.rmem_max[[:space:]]*=/{gsub(/[ \t]/,"",$2);print $2}' "$tmp" | tail -n1)"
  wmem_max="$(awk -F= '/^[[:space:]]*net\.core\.wmem_max[[:space:]]*=/{gsub(/[ \t]/,"",$2);print $2}' "$tmp" | tail -n1)"
  tcp_rmem="$(awk -F= '/^[[:space:]]*net\.ipv4\.tcp_rmem[[:space:]]*=/{sub(/^[ \t]+/,"",$2);print $2}' "$tmp" | tail -n1)"
  tcp_wmem="$(awk -F= '/^[[:space:]]*net\.ipv4\.tcp_wmem[[:space:]]*=/{sub(/^[ \t]+/,"",$2);print $2}' "$tmp" | tail -n1)"
  tr="$(extract_max_from_triplet "$tcp_rmem")"
  tw="$(extract_max_from_triplet "$tcp_wmem")"
  [[ -n "$rmem_max" && -n "$tr" ]] && (( rmem_max < tr )) && { err "参数校验失败：rmem_max < tcp_rmem 最大值"; return 1; }
  [[ -n "$wmem_max" && -n "$tw" ]] && (( wmem_max < tw )) && { err "参数校验失败：wmem_max < tcp_wmem 最大值"; return 1; }
  return 0
}

precheck(){
  echo
  echo -e "${BOLD}【预检查阶段】${NC}"
  line
  check_base_deps || return 1

  # ===== 内核与 BBR 状态 =====
  local kernel_ver bbr_available current_cc current_qdisc bbr_version
  kernel_ver="$(uname -r || true)"
  info "内核版本：$kernel_ver"
  
  # 检查 BBR 可用性
  bbr_available="no"
  if [[ -r /proc/sys/net/ipv4/tcp_available_congestion_control ]]; then
    local available_cc
    available_cc="$(cat /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null || true)"
    info "可用拥塞控制：$available_cc"
    if echo "$available_cc" | grep -qw bbr; then
      bbr_available="yes"
      ok "内核支持 BBR"
    else
      warn "内核未报告 BBR 支持"
    fi
  fi
  
  # 当前拥塞控制状态
  current_cc="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  current_qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  info "当前拥塞控制：$current_cc"
  info "当前队列算法：$current_qdisc"
  
  # BBR 模块版本检测
  if [[ "$current_cc" == "bbr" ]]; then
    ok "BBR 已启用"
    bbr_version="$(modinfo tcp_bbr 2>/dev/null | awk '/^version:/ {print $2}' || true)"
    if [[ -n "$bbr_version" ]]; then
      info "BBR 模块版本：$bbr_version"
    fi
  else
    warn "BBR 未启用（当前：$current_cc）"
  fi

  # ===== 虚拟化类型检测 =====
  local virt_type
  virt_type=""
  if cmd_exists systemd-detect-virt; then
    virt_type="$(systemd-detect-virt 2>/dev/null || true)"
  elif [[ -r /sys/hypervisor/type ]]; then
    virt_type="$(cat /sys/hypervisor/type 2>/dev/null || true)"
  elif grep -qi "docker\|lxc" /proc/1/cgroup 2>/dev/null; then
    virt_type="container"
  fi
  
  if [[ -n "$virt_type" && "$virt_type" != "none" ]]; then
    case "$virt_type" in
      kvm)       info "虚拟化类型：KVM（支持自定义内核）" ;;
      qemu)      info "虚拟化类型：QEMU（支持自定义内核）" ;;
      xen)       info "虚拟化类型：Xen（支持自定义内核）" ;;
      vmware)    info "虚拟化类型：VMware（支持自定义内核）" ;;
      microsoft) info "虚拟化类型：Hyper-V（支持自定义内核）" ;;
      openvz)    warn "虚拟化类型：OpenVZ（⚠️ 无法更换内核）" ;;
      lxc|lxc-libvirt) warn "虚拟化类型：LXC 容器（⚠️ 无法更换内核）" ;;
      container|docker) warn "虚拟化类型：容器环境（⚠️ 无法更换内核）" ;;
      *) info "虚拟化类型：$virt_type" ;;
    esac
  else
    info "虚拟化类型：物理机或未检测到"
  fi

  # ===== CPU 性能检测 =====
  local cpu_model cpu_cores
  cpu_model="$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || echo unknown)"
  cpu_cores="$(nproc 2>/dev/null || echo 1)"
  info "CPU：$cpu_model（${cpu_cores}核）"
  
  # AES-NI 指令集检测（加密性能关键）
  if grep -qw aes /proc/cpuinfo 2>/dev/null; then
    ok "AES-NI：已支持（加密性能优秀）"
  else
    warn "AES-NI：未检测到（加密性能可能较低，建议使用 ChaCha20）"
  fi

  # ===== 网卡检测 =====
  local nic speed driver ethtool_speed bw_hint
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  if [[ -n "${nic:-}" ]]; then
    info "默认网卡：$nic"
    
    # 获取驱动类型
    driver=""
    if [[ -r "/sys/class/net/$nic/device/driver" ]]; then
      driver="$(basename "$(readlink -f "/sys/class/net/$nic/device/driver")" 2>/dev/null || true)"
    elif [[ -r "/sys/class/net/$nic/device/uevent" ]]; then
      driver="$(awk -F= '/^DRIVER=/{print $2}' "/sys/class/net/$nic/device/uevent" 2>/dev/null || true)"
    fi
    
    # 尝试从 /sys 读取速度
    speed=""
    if [[ -r "/sys/class/net/$nic/speed" ]]; then
      speed="$(cat "/sys/class/net/$nic/speed" 2>/dev/null || true)"
    fi
    
    # 如果 /sys 返回 -1，尝试 ethtool
    ethtool_speed=""
    if [[ "$speed" == "-1" || -z "$speed" ]] && cmd_exists ethtool; then
      ethtool_speed="$(ethtool "$nic" 2>/dev/null | awk '/Speed:/ {print $2}' || true)"
      if [[ -n "$ethtool_speed" && "$ethtool_speed" != "Unknown!" ]]; then
        speed="$ethtool_speed"
      fi
    fi
    
    # 根据驱动类型推断带宽
    bw_hint=""
    case "${driver:-unknown}" in
      virtio_net|virtio-pci)
        bw_hint="10Gbps+（KVM/QEMU 虚拟化，实际取决于主机商限制）"
        ;;
      xen_netfront)
        bw_hint="取决于实例类型（Xen/AWS EC2 旧实例）"
        ;;
      ena)
        bw_hint="最高 100Gbps（AWS ENA 增强网络）"
        ;;
      hv_netvsc)
        bw_hint="取决于实例类型（Hyper-V/Azure）"
        ;;
      vmxnet3)
        bw_hint="10Gbps（VMware 虚拟化）"
        ;;
      veth)
        bw_hint="容器网络（Docker/LXC），带宽由主机决定"
        ;;
      *)
        bw_hint=""
        ;;
    esac
    
    # 输出检测结果
    if [[ -n "$driver" ]]; then
      info "网卡驱动：$driver"
    fi
    
    if [[ -n "$speed" && "$speed" != "-1" && "$speed" != "Unknown!" ]]; then
      info "网卡速率：${speed}Mbps"
    elif [[ -n "$bw_hint" ]]; then
      info "推测带宽上限：$bw_hint"
      echo -e "  ${YELLOW}💡 建议：选择「VPS 极致带宽版（虚拟网卡）」方案以最大化利用带宽${NC}"
    else
      info "网卡速率：虚拟网卡（无法检测物理链路速度）"
    fi
  fi

  # ===== UDP 端口检测 =====
  line
  info "正在检测 UDP 连通性..."
  local udp_test_result
  # 检查是否有 UDP 相关的 iptables 规则阻止
  if cmd_exists iptables; then
    local udp_drop_rules
    udp_drop_rules="$(iptables -L -n 2>/dev/null | grep -i "udp.*drop\|drop.*udp" | head -3 || true)"
    if [[ -n "$udp_drop_rules" ]]; then
      warn "检测到 UDP 丢弃规则（可能影响 Hysteria2 等 UDP 代理）："
      echo "$udp_drop_rules" | head -3
    else
      ok "未检测到 UDP 阻止规则"
    fi
  fi

  # ===== 端口限速检测（tc qdisc） =====
  if cmd_exists tc && [[ -n "${nic:-}" ]]; then
    local tc_rules
    tc_rules="$(tc qdisc show dev "$nic" 2>/dev/null || true)"
    if echo "$tc_rules" | grep -qiE "tbf|htb|cake|police"; then
      warn "检测到流量整形规则（可能存在端口限速）："
      echo "$tc_rules" | grep -iE "tbf|htb|cake|police" | head -3
    else
      ok "未检测到端口限速规则"
    fi
  fi

  line
  [[ -w /etc/sysctl.d ]] || { err "/etc/sysctl.d 不可写"; return 1; }
  sysctl -a >/dev/null 2>&1 || { err "sysctl 读取失败"; return 1; }

  ok "预检查通过"
  return 0
}

conflict_check(){
  echo
  echo -e "${BOLD}【冲突检测】sysctl 重复键${NC}"
  line
  local files=()
  [[ -f /etc/sysctl.conf ]] && files+=(/etc/sysctl.conf)
  while IFS= read -r -d '' f; do files+=("$f"); done < <(find /etc/sysctl.d -maxdepth 1 -type f -name "*.conf" -print0 2>/dev/null | sort -z)
  [[ ${#files[@]} -eq 0 ]] && { warn "未找到配置文件"; return 0; }

  local out
  out="$(
    awk '
      function trim(s){gsub(/^[ \t]+|[ \t]+$/,"",s); return s}
      {
        line=$0; sub(/#.*/,"",line)
        if (line ~ /^[ \t]*$/ || line !~ /=/) next
        split(line,a,"="); key=trim(a[1]); if(key=="") next
        kf=key SUBSEP FILENAME
        if (!(kf in seen)) { seen[kf]=1; cnt[key]++; files[key]=files[key]?files[key] "," FILENAME:FILENAME }
      }
      END{ for(k in cnt) if(cnt[k]>1) print k " => " files[k] }
    ' "${files[@]}" | sort
  )"

  if [[ -z "$out" ]]; then
    ok "未发现重复键冲突"
  else
    warn "发现重复键："
    echo "$out"
    echo
    read -rp "是否尝试自动修复（注释掉非管理文件中的冗余项）？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      resolve_conflicts "$out"
    fi
  fi
  line
}

resolve_conflicts(){
  local conflict_out="$1"
  [[ -z "$conflict_out" ]] && return 0

  local hdir
  hdir="$(save_last_and_history_snapshot)"
  info "修复前快照：$hdir"

  info "正在准备修复冲突..."
  local key file_list f
  while IFS= read -r row; do
    [[ -z "$row" ]] && continue
    key="${row%% => *}"
    file_list="${row#* => }"
    
    IFS=',' read -ra file_array <<< "$file_list"
    for f in "${file_array[@]}"; do
      # 排除脚本管理的文件
      if [[ "$f" == "$ACTIVE_FILE" || "$f" == "$BBR_SYSCTL_FILE" ]]; then
        continue
      fi
      
      # 全量转义正则特殊字符
      local escaped_key
      escaped_key="$(escape_regex "$key")"

      if grep -qiE "^[[:space:]]*${escaped_key}[[:space:]]*=" "$f"; then
        if ! grep -q "commented by net-tune-pro repair" "$f"; then
          info "在 $f 中注释掉冲突键：$key"
          sed -i -E "s/^([[:space:]]*${escaped_key}[[:space:]]*=.*)$/# \1 # commented by net-tune-pro repair/" "$f"
        fi
      fi
    done
  done <<< "$conflict_out"
  
  ok "自动修复尝试完成。建议再次运行冲突检测。"
}

# ===================== 快照/回滚/永久基线 =====================
save_last_and_history_snapshot(){
  local stamp hdir
  stamp="$(ts)"
  rm -rf "${LAST_APPLY_DIR:?}/"* 2>/dev/null || true
  mkdir -p "$LAST_APPLY_DIR/sysctl.d"
  hdir="${HISTORY_DIR}/${stamp}"
  mkdir -p "$hdir/sysctl.d"

  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$LAST_APPLY_DIR/sysctl.conf" || true
  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$hdir/sysctl.conf" || true
  cp -a /etc/sysctl.d/*.conf "$LAST_APPLY_DIR/sysctl.d/" 2>/dev/null || true
  cp -a /etc/sysctl.d/*.conf "$hdir/sysctl.d/" 2>/dev/null || true

  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$LAST_APPLY_DIR/managed-active.conf" || true
  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$hdir/managed-active.conf" || true
  [[ -f "$BBR_SYSCTL_FILE" ]] && cp -a "$BBR_SYSCTL_FILE" "$LAST_APPLY_DIR/managed-bbr.conf" || true
  [[ -f "$BBR_SYSCTL_FILE" ]] && cp -a "$BBR_SYSCTL_FILE" "$hdir/managed-bbr.conf" || true
  [[ -f "$MODULES_CONF" ]] && cp -a "$MODULES_CONF" "$LAST_APPLY_DIR/managed-modules.conf" || true
  [[ -f "$MODULES_CONF" ]] && cp -a "$MODULES_CONF" "$hdir/managed-modules.conf" || true

  sysctl -a 2>/dev/null > "$LAST_APPLY_DIR/runtime-sysctl-all.txt" || true
  sysctl -a 2>/dev/null > "$hdir/runtime-sysctl-all.txt" || true
  echo "$hdir"
}

clean_old_snapshots(){
  local keep_count="${1:-20}"
  local snapshots count to_delete
  snapshots=($(ls -1d "${HISTORY_DIR}/"* 2>/dev/null | sort))
  count=${#snapshots[@]}
  
  if (( count <= keep_count )); then
    info "当前快照数量：$count（保留阈值：$keep_count），无需清理"
    return 0
  fi
  
  to_delete=$((count - keep_count))
  info "将清理 $to_delete 个旧快照，保留最近 $keep_count 个"
  
  for ((i=0; i<to_delete; i++)); do
    rm -rf "${snapshots[$i]}"
    info "已删除：${snapshots[$i]}"
  done
  
  ok "清理完成，当前剩余：$keep_count 个快照"
}

rollback_last_apply_point(){
  if [[ -f "$LAST_APPLY_DIR/managed-active.conf" ]]; then
    cp -a "$LAST_APPLY_DIR/managed-active.conf" "$ACTIVE_FILE"
  else
    rm -f "$ACTIVE_FILE"
  fi
  if [[ -f "$LAST_APPLY_DIR/managed-bbr.conf" ]]; then
    cp -a "$LAST_APPLY_DIR/managed-bbr.conf" "$BBR_SYSCTL_FILE"
  fi
  if [[ -f "$LAST_APPLY_DIR/managed-modules.conf" ]]; then
    cp -a "$LAST_APPLY_DIR/managed-modules.conf" "$MODULES_CONF"
  fi

  if sysctl --system >/tmp/net-tune-v3-rollback.log 2>&1; then
    ok "已回滚到上一次应用点（仅管理文件）"
  else
    err "回滚失败，日志：/tmp/net-tune-v3-rollback.log"
    return 1
  fi
}

save_permanent_baseline(){
  local marker="${PERM_DIR}/BASELINE_LOCK"
  [[ -f "$marker" ]] && { warn "永久初始备份已存在：$PERM_DIR"; return 0; }

  mkdir -p "$PERM_DIR/sysctl.d"
  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$PERM_DIR/sysctl.conf" || true
  cp -a /etc/sysctl.d/*.conf "$PERM_DIR/sysctl.d/" 2>/dev/null || true
  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$PERM_DIR/managed-active.conf" || true
  [[ -f "$BBR_SYSCTL_FILE" ]] && cp -a "$BBR_SYSCTL_FILE" "$PERM_DIR/managed-bbr.conf" || true
  [[ -f "$MODULES_CONF" ]] && cp -a "$MODULES_CONF" "$PERM_DIR/managed-modules.conf" || true

  # 注意：heredoc 未加引号，变量会在写入时展开（记录创建时信息）
  cat > "$marker" <<LOCK
CreatedAt=$(date '+%F %T')
Host=$(hostname)
Kernel=$(uname -r)
Note=Permanent baseline, do not overwrite automatically.
LOCK
  chmod 700 "$PERM_DIR" || true
  chmod 600 "$marker" || true
  ok "永久初始备份创建完成：$PERM_DIR"

  if cmd_exists chattr; then
    read -rp "是否给 BASELINE_LOCK 添加不可变属性（chattr +i）？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      if chattr +i "$marker" 2>/dev/null; then
        ok "已加锁"
      else
        warn "chattr +i 失败（文件系统可能不支持）"
      fi
    fi
  fi
}

restore_permanent_baseline(){
  local marker="${PERM_DIR}/BASELINE_LOCK"
  [[ -f "$marker" ]] || { err "未找到永久初始备份"; return 1; }

  save_last_and_history_snapshot >/dev/null || true
  if [[ -f "$PERM_DIR/managed-active.conf" ]]; then
    cp -a "$PERM_DIR/managed-active.conf" "$ACTIVE_FILE"
  else
    rm -f "$ACTIVE_FILE"
  fi
  if [[ -f "$PERM_DIR/managed-bbr.conf" ]]; then
    cp -a "$PERM_DIR/managed-bbr.conf" "$BBR_SYSCTL_FILE"
  fi
  if [[ -f "$PERM_DIR/managed-modules.conf" ]]; then
    cp -a "$PERM_DIR/managed-modules.conf" "$MODULES_CONF"
  fi

  if sysctl --system >/tmp/net-tune-v3-restore-baseline.log 2>&1; then
    ok "已回滚到永久初始配置（管理文件范围）"
  else
    err "回滚失败，日志：/tmp/net-tune-v3-restore-baseline.log"
    return 1
  fi
}

# ===================== 网络方案应用（原子写入） =====================
render_profile_to_tmp(){
  local p="$1" tmp="$2"
  { common_base; emit_profile "$p"; } > "$tmp"
}

apply_profile(){
  local p="$1" tmp hdir
  tmp="$(mktemp /tmp/net-tune-v3.XXXXXX.conf)"
  render_profile_to_tmp "$p" "$tmp" || { rm -f "$tmp"; err "未知方案"; return 1; }
  validate_profile_semantics "$tmp" || { rm -f "$tmp"; return 1; }

  hdir="$(save_last_and_history_snapshot)"
  info "快照已保存：$hdir"

  install -m 0644 "$tmp" "${ACTIVE_FILE}.new"
  mv -f "${ACTIVE_FILE}.new" "$ACTIVE_FILE"
  rm -f "$tmp"

  if ! sysctl -p "$ACTIVE_FILE" >/tmp/net-tune-v3-apply-single.log 2>&1; then
    err "单文件校验失败：/tmp/net-tune-v3-apply-single.log"
    rollback_last_apply_point >/dev/null 2>&1 || true
    return 1
  fi
  if ! sysctl --system >/tmp/net-tune-v3-apply.log 2>&1; then
    err "全量加载失败（可能外部冲突）：/tmp/net-tune-v3-apply.log"
    rollback_last_apply_point >/dev/null 2>&1 || true
    return 1
  fi

  CURRENT_PROFILE="$p"
  ok "方案已应用：$p"
  log "APPLY profile=$p success"
}

# ===================== BBR 功能（中文） =====================
clean_bbr_sysctl_conf(){
  touch "$BBR_SYSCTL_FILE"
  sed -i '/^[[:space:]]*net\.core\.default_qdisc[[:space:]]*=/d' "$BBR_SYSCTL_FILE"
  sed -i '/^[[:space:]]*net\.ipv4\.tcp_congestion_control[[:space:]]*=/d' "$BBR_SYSCTL_FILE"
}

load_qdisc_module(){
  local qdisc_name="$1"
  local module_name="sch_$qdisc_name"
  local current_qdisc
  current_qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo fq_codel)"

  if sysctl -w net.core.default_qdisc="$qdisc_name" >/dev/null 2>&1; then
    sysctl -w net.core.default_qdisc="$current_qdisc" >/dev/null 2>&1 || true
    return 0
  fi

  if lsmod | grep -q "^${module_name//-/_}"; then
    return 0
  fi

  info "尝试加载模块：$module_name"
  if modprobe "$module_name" 2>/dev/null; then
    ok "模块加载成功：$module_name"
    return 0
  else
    warn "模块加载失败，内核可能不支持：$module_name"
    return 1
  fi
}

bbr_qdisc_apply(){
  local algo="$1" qdisc="$2"
  save_last_and_history_snapshot >/dev/null || true

  load_qdisc_module "$qdisc" || true
  sysctl -w net.core.default_qdisc="$qdisc" >/dev/null 2>&1 || true
  sysctl -w net.ipv4.tcp_congestion_control="$algo" >/dev/null 2>&1 || true

  local new_qdisc new_algo
  new_qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  new_algo="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"

  if [[ "$new_qdisc" == "$qdisc" && "$new_algo" == "$algo" ]]; then
    ok "已立即生效：队列=$new_qdisc，拥塞控制=$new_algo"
  else
    err "应用失败：期望 $qdisc/$algo，实际 $new_qdisc/$new_algo"
    return 1
  fi

  read -rp "是否永久保存到 $BBR_SYSCTL_FILE ？[y/N]: " save
  if [[ "${save:-N}" =~ ^[Yy]$ ]]; then
    clean_bbr_sysctl_conf
    echo "net.core.default_qdisc=$qdisc" >> "$BBR_SYSCTL_FILE"
    echo "net.ipv4.tcp_congestion_control=$algo" >> "$BBR_SYSCTL_FILE"
    sysctl --system >/tmp/net-tune-v3-bbr-save.log 2>&1 || true

    if [[ "$qdisc" == "fq" || "$qdisc" == "fq_codel" ]]; then
      rm -f "$MODULES_CONF"
    else
      echo "sch_$qdisc" > "$MODULES_CONF"
    fi
    ok "已永久保存"
  else
    warn "未永久保存，重启后可能恢复"
  fi
}

get_installed_joey_kernel(){
  dpkg -l 2>/dev/null | awk '/linux-image/ && /joeyblog/ {print $2}' | sed 's/linux-image-//' | head -n1
}

update_bootloader(){
  info "正在更新引导加载器..."
  if cmd_exists update-grub; then
    if update-grub; then ok "update-grub 成功"; return 0; else err "update-grub 失败"; return 1; fi
  else
    warn "未找到 update-grub。系统可能使用其他引导（如 U-Boot），请按系统文档确认。"
    return 0
  fi
}

install_packages_from_tmp(){
  ls /tmp/linux-*.deb >/dev/null 2>&1 || { err "未找到 /tmp/linux-*.deb"; return 1; }

  local installed
  installed="$(dpkg -l 2>/dev/null | awk '/joeyblog/ {print $2}' | tr '\n' ' ')"
  if [[ -n "$installed" ]]; then
    info "正在卸载旧版内核：$installed"
    apt-get remove --purge -y $installed >/dev/null 2>&1 || true
  fi

  info "正在安装新内核..."
  if dpkg -i /tmp/linux-*.deb && update_bootloader; then
    ok "内核安装完成"
    read -rp "是否立即重启以加载新内核？[y/N]: " rb
    if [[ "${rb:-N}" =~ ^[Yy]$ ]]; then
      reboot
    else
      warn "请稍后手动重启：sudo reboot"
    fi
  else
    err "安装或引导更新失败，请检查系统状态"
    return 1
  fi
}

install_latest_joey_kernel(){
  is_debian_like || { err "该功能仅支持 Debian/Ubuntu（apt-get）"; return 1; }
  ensure_bbr_deps_debian || return 1
  [[ "$ARCH" == "aarch64" || "$ARCH" == "x86_64" ]] || { err "仅支持 aarch64/x86_64，当前：$ARCH"; return 1; }

  local api="https://api.github.com/repos/byJoey/Actions-bbr-v3/releases"
  local data arch_filter latest_tag core_latest installed urls

  info "正在从 GitHub 获取发布信息..."
  data="$(curl -fsSL "$api" || true)"
  [[ -n "$data" ]] || { err "获取发布信息失败"; return 1; }

  arch_filter="x86_64"; [[ "$ARCH" == "aarch64" ]] && arch_filter="arm64"
  latest_tag="$(echo "$data" | jq -r --arg f "$arch_filter" 'map(select(.tag_name|test($f;"i")))|sort_by(.published_at)|.[-1].tag_name')"
  [[ -n "$latest_tag" && "$latest_tag" != "null" ]] || { err "未找到匹配当前架构的版本"; return 1; }

  installed="$(get_installed_joey_kernel)"
  core_latest="${latest_tag#x86_64-}"; core_latest="${core_latest#arm64-}"
  info "最新版本：$latest_tag"
  info "当前已安装：${installed:-未安装}"

  if [[ -n "$installed" && "$installed" == "$core_latest"* ]]; then
    ok "当前已是最新版本"
    return 0
  fi

  urls="$(echo "$data" | jq -r --arg t "$latest_tag" '.[]|select(.tag_name==$t)|.assets[].browser_download_url')"
  rm -f /tmp/linux-*.deb
  while IFS= read -r u; do
    [[ -z "$u" ]] && continue
    info "正在下载：$u"
    wget -q --show-progress "$u" -P /tmp/ || { err "下载失败：$u"; return 1; }
  done <<< "$urls"

  install_packages_from_tmp
}

install_specific_joey_kernel(){
  is_debian_like || { err "该功能仅支持 Debian/Ubuntu"; return 1; }
  ensure_bbr_deps_debian || return 1
  [[ "$ARCH" == "aarch64" || "$ARCH" == "x86_64" ]] || { err "仅支持 aarch64/x86_64"; return 1; }

  local api="https://api.github.com/repos/byJoey/Actions-bbr-v3/releases"
  local data arch_filter selected idx urls
  local -a tags

  data="$(curl -fsSL "$api" || true)"
  [[ -n "$data" ]] || { err "获取发布信息失败"; return 1; }

  arch_filter="x86_64"; [[ "$ARCH" == "aarch64" ]] && arch_filter="arm64"
  mapfile -t tags < <(echo "$data" | jq -r --arg f "$arch_filter" '.[]|select(.tag_name|test($f;"i"))|.tag_name')
  [[ ${#tags[@]} -gt 0 ]] || { err "未找到可用版本"; return 1; }

  echo "可选版本列表："
  for i in "${!tags[@]}"; do
    echo " $((i+1))) ${tags[$i]}"
  done
  read -rp "请输入要安装的版本编号： " idx
  [[ "$idx" =~ ^[0-9]+$ ]] || { err "输入无效"; return 1; }
  (( idx>=1 && idx<=${#tags[@]} )) || { err "编号超出范围"; return 1; }

  selected="${tags[$((idx-1))]}"
  info "已选择版本：$selected"

  urls="$(echo "$data" | jq -r --arg t "$selected" '.[]|select(.tag_name==$t)|.assets[].browser_download_url')"
  rm -f /tmp/linux-*.deb
  while IFS= read -r u; do
    [[ -z "$u" ]] && continue
    info "正在下载：$u"
    wget -q --show-progress "$u" -P /tmp/ || { err "下载失败：$u"; return 1; }
  done <<< "$urls"

  install_packages_from_tmp
}

check_bbr_v3_status(){
  local info_mod version algo qdisc
  info_mod="$(modinfo tcp_bbr 2>/dev/null || true)"
  if [[ -z "$info_mod" ]]; then
    warn "未检测到 tcp_bbr 模块信息（可能未加载或内核不包含）"
  else
    version="$(awk '/^version:/ {print $2}' <<< "$info_mod" | head -n1)"
    [[ -n "$version" ]] && info "tcp_bbr 模块 version：$version" || info "检测到 tcp_bbr 模块（未读到 version 字段）"
  fi

  algo="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  echo "当前拥塞控制：$algo"
  echo "当前队列算法：$qdisc"

  if [[ "$algo" == "bbr" ]]; then ok "BBR 已启用"; else warn "当前未启用 bbr"; fi
}

uninstall_joey_kernel(){
  is_debian_like || { err "该功能仅支持 Debian/Ubuntu"; return 1; }
  local pkgs
  pkgs="$(dpkg -l 2>/dev/null | awk '/joeyblog/ {print $2}' | tr '\n' ' ')"
  if [[ -z "$pkgs" ]]; then
    warn "未找到 joeyblog 内核包"
    return 0
  fi

  info "将卸载以下内核包：$pkgs"
  apt-get remove --purge -y $pkgs || { err "卸载失败"; return 1; }
  update_bootloader || true
  ok "卸载完成，请重启系统"
}

# ===================== 状态/监控 =====================
show_status(){
  echo
  echo -e "${BOLD}【当前状态】${NC}"
  line
  echo "网络方案托管文件：$ACTIVE_FILE"
  echo "BBR托管文件     ：$BBR_SYSCTL_FILE"
  echo "模块配置文件    ：$MODULES_CONF"
  echo "当前会话方案    ：${CURRENT_PROFILE:-unknown}"
  line
  [[ -f "$ACTIVE_FILE" ]] && { echo "[网络方案文件内容]"; cat "$ACTIVE_FILE"; line; }
  [[ -f "$BBR_SYSCTL_FILE" ]] && { echo "[BBR文件内容]"; cat "$BBR_SYSCTL_FILE"; line; }

  sysctl \
    net.core.default_qdisc \
    net.ipv4.tcp_congestion_control \
    net.core.netdev_max_backlog \
    net.core.somaxconn \
    net.ipv4.tcp_max_syn_backlog \
    net.core.rmem_max \
    net.core.wmem_max \
    net.ipv4.tcp_rmem \
    net.ipv4.tcp_wmem 2>/dev/null || true
}

watch_metrics(){
  info "实时监控中（Ctrl+C 返回）"
  sleep 1
  while true; do
    clear
    echo -e "${BOLD}===== $(date '+%F %T') =====${NC}"
    echo "[softnet_stat 丢包列（第2列）前8行]"
    awk '{print NR ": " $2}' /proc/net/softnet_stat | head -n 8
    echo
    echo "[ss -s]"
    ss -s || true
    echo
    nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
    echo "[默认网卡统计: ${nic:-unknown}]"
    [[ -n "${nic:-}" ]] && ip -s link show "$nic" || ip -s link | sed -n '1,40p'
    echo
    echo "[内存]"
    free -h || true
    sleep 2
  done
}

# ===================== Virtio/KVM 网卡优化 =====================
apply_virtio_optimizations(){
  echo
  echo -e "${BOLD}【Virtio/KVM 网卡优化】${NC}"
  line

  local nic driver
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  if [[ -z "${nic:-}" ]]; then
    err "未检测到默认网卡"
    return 1
  fi
  info "默认网卡：$nic"

  # 检测驱动类型
  driver=""
  if [[ -r "/sys/class/net/$nic/device/driver" ]]; then
    driver="$(basename "$(readlink -f "/sys/class/net/$nic/device/driver")" 2>/dev/null || true)"
  elif [[ -r "/sys/class/net/$nic/device/uevent" ]]; then
    driver="$(awk -F= '/^DRIVER=/{print $2}' "/sys/class/net/$nic/device/uevent" 2>/dev/null || true)"
  fi
  info "网卡驱动：${driver:-unknown}"

  if [[ "${driver:-}" != "virtio_net" && "${driver:-}" != "virtio-pci" ]]; then
    warn "当前网卡驱动不是 virtio_net，部分优化可能不适用"
    read -rp "是否继续？[y/N]: " yn
    if [[ ! "${yn:-N}" =~ ^[Yy]$ ]]; then
      return 0
    fi
  fi

  local cpu_count
  cpu_count="$(nproc 2>/dev/null || echo 1)"
  info "CPU 核心数：$cpu_count"

  # 自动安装 ethtool（多数优化依赖它）
  if ! cmd_exists ethtool; then
    warn "未检测到 ethtool，正在尝试自动安装..."
    if is_debian_like; then
      apt-get update -y >/dev/null 2>&1 || true
      apt-get install -y ethtool >/dev/null 2>&1 && ok "ethtool 安装成功" || warn "ethtool 安装失败，部分优化将跳过"
    elif cmd_exists yum; then
      yum install -y ethtool >/dev/null 2>&1 && ok "ethtool 安装成功" || warn "ethtool 安装失败，部分优化将跳过"
    else
      warn "无法自动安装 ethtool，请手动安装：apt install ethtool 或 yum install ethtool"
    fi
  fi

  line

  # ===== 1. Virtio 多队列 (Multiqueue) =====
  echo -e "${BOLD}[1/5] Virtio 多队列${NC}"
  if cmd_exists ethtool; then
    local max_combined current_combined
    max_combined="$(ethtool -l "$nic" 2>/dev/null | awk '/Combined:/{v=$2} END{print v}')"
    current_combined="$(ethtool -l "$nic" 2>/dev/null | awk '/Combined:/{print $2; exit}')"
    if [[ -n "$max_combined" && "$max_combined" -gt 1 ]] 2>/dev/null; then
      local target=$((cpu_count < max_combined ? cpu_count : max_combined))
      if ethtool -L "$nic" combined "$target" 2>/dev/null; then
        ok "多队列已设置为 $target（最大 $max_combined）"
      else
        warn "多队列设置失败（当前：${current_combined:-unknown}）"
      fi
    else
      info "网卡不支持多队列或已是单队列"
    fi
  else
    warn "未安装 ethtool，跳过多队列设置"
  fi

  # ===== 2. RPS / RFS（软件级多核分发） =====
  echo -e "${BOLD}[2/5] RPS / RFS 多核分发${NC}"
  local rps_mask
  rps_mask="$(printf '%x' $(( (1 << cpu_count) - 1 )))"

  local rps_applied=0
  local queue_dir
  for queue_dir in /sys/class/net/"$nic"/queues/rx-*; do
    [[ -d "$queue_dir" ]] || continue
    if echo "$rps_mask" > "$queue_dir/rps_cpus" 2>/dev/null; then
      rps_applied=$((rps_applied + 1))
    fi
    if [[ -w "$queue_dir/rps_flow_cnt" ]]; then
      echo 4096 > "$queue_dir/rps_flow_cnt" 2>/dev/null || true
    fi
  done

  if [[ -w /proc/sys/net/core/rps_sock_flow_entries ]]; then
    echo 32768 > /proc/sys/net/core/rps_sock_flow_entries 2>/dev/null || true
  fi

  if (( rps_applied > 0 )); then
    ok "RPS 已应用到 $rps_applied 个接收队列（掩码：$rps_mask）"
    ok "RFS 已启用（flow_entries=32768，flow_cnt=4096）"
  else
    warn "RPS 设置失败（可能无权限）"
  fi

  # ===== 3. 网卡 Ring Buffer 加大 =====
  echo -e "${BOLD}[3/5] Ring Buffer${NC}"
  if cmd_exists ethtool; then
    local max_rx max_tx
    max_rx="$(ethtool -g "$nic" 2>/dev/null | awk '/^Pre-set/,/^Current/{if(/RX:/){print $2}}' | head -1)"
    max_tx="$(ethtool -g "$nic" 2>/dev/null | awk '/^Pre-set/,/^Current/{if(/TX:/){print $2}}' | head -1)"
    if [[ -n "$max_rx" && -n "$max_tx" ]]; then
      if ethtool -G "$nic" rx "$max_rx" tx "$max_tx" 2>/dev/null; then
        ok "Ring Buffer 已设为最大值（RX=$max_rx TX=$max_tx）"
      else
        info "Ring Buffer 设置失败或已是最大值"
      fi
    else
      info "Ring Buffer 信息读取失败，跳过"
    fi
  else
    warn "未安装 ethtool，跳过 Ring Buffer 设置"
  fi

  # ===== 4. 硬件卸载（GSO/GRO/TSO） =====
  echo -e "${BOLD}[4/5] 硬件卸载检查${NC}"
  if cmd_exists ethtool; then
    for feat in gso gro tso; do
      # ethtool -k 输出的是长名称，需要映射
      local long_feat=""
      case "$feat" in
        gso) long_feat="generic-segmentation-offload" ;;
        gro) long_feat="generic-receive-offload" ;;
        tso) long_feat="tcp-segmentation-offload" ;;
      esac

      local status
      # 使用 awk 提取状态，避免 grep 找不到时返回 1 导致脚本退出 (set -e)
      status="$(ethtool -k "$nic" 2>/dev/null | awk -v f="$long_feat" '$1 == f":" {print $2}')"
      
      if [[ "$status" == "off" ]]; then
        if ethtool -K "$nic" "$feat" on 2>/dev/null; then
          ok "$feat 已开启"
        else
          warn "$feat 开启失败（可能不支持）"
        fi
      else
        ok "$feat 已是开启状态"
      fi
    done
  else
    warn "未安装 ethtool，跳过硬件卸载检查"
  fi

  # ===== 5. 中断合并（减少 CPU 开销） =====
  echo -e "${BOLD}[5/5] 中断合并${NC}"
  if cmd_exists ethtool; then
    if ethtool -C "$nic" adaptive-rx on adaptive-tx on 2>/dev/null; then
      ok "自适应中断合并已开启"
    else
      info "自适应中断合并设置失败（virtio 可能不支持，这是正常的）"
    fi
  else
    warn "未安装 ethtool，跳过中断合并设置"
  fi

  line
  ok "Virtio/KVM 网卡优化完成"
  warn "注意：以上设置重启后失效，建议添加到 /etc/rc.local 或 systemd 服务中持久化"
  log "VIRTIO_OPTIMIZE nic=$nic driver=${driver:-unknown} cpus=$cpu_count"
}

# ===================== 脚本更新 =====================
update_script(){
  echo
  echo -e "${BOLD}【脚本更新】${NC}"
  line
  info "当前版本：$VERSION"
  info "正在检查新版本..."

  local update_url="https://raw.githubusercontent.com/suxayii/Throttle/master/install.sh"
  local tmp_file="/tmp/net-tune-pro-update.sh"

  if cmd_exists curl; then
    curl -fsSL "$update_url" -o "$tmp_file"
  elif cmd_exists wget; then
    wget -qO "$tmp_file" "$update_url"
  else
    err "未找到 curl 或 wget，无法下载更新"
    return 1
  fi

  if [[ ! -s "$tmp_file" ]]; then
    err "下载失败或文件为空，请检查网络连接"
    rm -f "$tmp_file"
    return 1
  fi

  # 简单的内容比对
  if cmp -s "$0" "$tmp_file"; then
    ok "当前已是最新版本"
    rm -f "$tmp_file"
    return 0
  else
    # 尝试提取新版本号（如果脚本里有定义 VERSION）
    local new_ver
    new_ver="$(grep '^VERSION=' "$tmp_file" | head -1 | cut -d'"' -f2)"
    [[ -z "$new_ver" ]] && new_ver="未知"
    
    info "发现新版本：$new_ver"
    read -rp "是否更新脚本？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      mv "$tmp_file" "$0"
      chmod +x "$0"
      ok "脚本更新成功，即将重新加载..."
      sleep 2
      exec bash "$0"
    else
      info "已取消更新"
      rm -f "$tmp_file"
    fi
  fi
}

# ===================== 菜单 =====================
choose_profile_menu(){
  local p p_name
  while true; do
    clear
    echo -e "${BOLD}【选择并应用网络优化方案】${NC}"
    line
    echo "1) 平衡版（通用推荐）"
    echo "2) 激进版（高并发/高PPS）"
    echo "3) 激进稳妥版（推荐）"
    echo "4) UDP 专项版（QUIC/UDP 优化）"
    echo "5) 流媒体代理版（VLESS/Reality TCP）"
    echo "6) 低内存保守版（1C/1G）"
    echo "7) 低内存保守版（2C/2G）"
    echo "8) 高带宽版（1G口）"
    echo "9) 高带宽版（10G口）"
    echo "10) VPS 极致带宽版（虚拟网卡）"
    echo "0) 返回"
    line
    read -rp "请输入选项 [0-10]: " c

    case "$c" in
      1) p="balanced"; p_name="平衡版（通用推荐）" ;;
      2) p="aggressive"; p_name="激进版（高并发/高PPS）" ;;
      3) p="aggressive_safe"; p_name="激进稳妥版（推荐）" ;;
      4) p="udp_quic"; p_name="UDP 专项版（QUIC/UDP 优化）" ;;
      5) p="streaming"; p_name="流媒体代理版（VLESS/Reality TCP）" ;;
      6) p="low_1c1g"; p_name="低内存保守版（1C/1G）" ;;
      7) p="low_2c2g"; p_name="低内存保守版（2C/2G）" ;;
      8) p="bw_1g"; p_name="高带宽版（1G口）" ;;
      9) p="bw_10g"; p_name="高带宽版（10G口）" ;;
      10) p="vps_max"; p_name="VPS 极致带宽版（虚拟网卡）" ;;
      0) return ;;
      *) warn "无效输入"; sleep 1; continue ;;
    esac

    precheck || { pause; continue; }
    conflict_check
    read -rp "确认应用「$p_name」吗？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      apply_profile "$p" && ok "已应用：$p_name"
    else
      warn "已取消"
    fi
    pause
    return
  done
}

bbr_menu(){
  while true; do
    clear
    echo -e "${BOLD}【BBR 内核与队列管理】${NC}"
    line
    echo "1) 安装/更新 BBR v3（最新版）"
    echo "2) 安装指定版本 BBR 内核"
    echo "3) 检查 BBR v3 状态"
    echo "4) 启用 BBR + FQ"
    echo "5) 启用 BBR + FQ_CODEL"
    echo "6) 启用 BBR + FQ_PIE"
    echo "7) 启用 BBR + CAKE"
    echo "8) 卸载 joeyblog 内核"
    echo "0) 返回"
    line
    read -rp "请输入选项 [0-8]: " a
    case "$a" in
      1) install_latest_joey_kernel ;;
      2) install_specific_joey_kernel ;;
      3) check_bbr_v3_status ;;
      4) bbr_qdisc_apply "bbr" "fq" ;;
      5) bbr_qdisc_apply "bbr" "fq_codel" ;;
      6) bbr_qdisc_apply "bbr" "fq_pie" ;;
      7) bbr_qdisc_apply "bbr" "cake" ;;
      8) uninstall_joey_kernel ;;
      0) return ;;
      *) warn "无效输入" ;;
    esac
    pause
  done
}

main_menu(){
  while true; do
    clear
    echo -e "${BOLD}${BLUE}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║   Net Tune Pro v3 中文版（网络优化 + BBR 全功能）      ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo "1) 预检查阶段"
    echo "2) 冲突检测（sysctl 重复键）"
    echo "3) 应用网络优化方案（原子写入）"
    echo "4) BBR 内核/队列管理（安装/升级/卸载/启用）"
    echo "5) 查看当前状态"
    echo "6) 实时监控"
    echo "7) 回滚到上一次应用点"
    echo "8) 创建永久初始备份（仅首次）"
    echo "9) 回滚到永久初始配置（管理文件范围）"
    echo "10) 查看历史快照列表"
    echo "11) 清理旧快照（保留最近20个）"
    echo "12) Virtio/KVM 网卡优化"
    echo "13) 更新脚本"
    echo "0) 退出"
    line
    read -rp "请输入选项: " ch
    case "$ch" in
      1) precheck; pause ;;
      2) conflict_check; pause ;;
      3) choose_profile_menu ;;
      4) bbr_menu ;;
      5) show_status; pause ;;
      6) watch_metrics ;;
      7) rollback_last_apply_point; pause ;;
      8) save_permanent_baseline; pause ;;
      9)
        read -rp "确认回滚到永久初始配置？[y/N]: " yn
        if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
          restore_permanent_baseline
        else
          warn "已取消"
        fi
        pause
        ;;
      10) ls -1 "$HISTORY_DIR" 2>/dev/null | sort || true; pause ;;
      11) clean_old_snapshots 20; pause ;;
      12) apply_virtio_optimizations; pause ;;
      13) update_script; pause ;;
      0) ok "已退出"; exit 0 ;;
      *) warn "无效输入"; sleep 1 ;;
    esac
  done
}

need_root
check_base_deps
main_menu
EOF

chmod +x /root/net-tune-pro-v3-zh.sh
bash /root/net-tune-pro-v3-zh.sh
