#!/usr/bin/env bash
set -euo pipefail

# ===================== 基础路径 =====================
ACTIVE_FILE="/etc/sysctl.d/99-net-tune-pro-v3.conf"            # 网络方案托管文件
PROFILE_STATE_FILE="/etc/net-tune-pro-profile-name"            # 当前应用方案名称记录

BACKUP_DIR="/root/sysctl-backups-v3"
PERM_DIR="/root/sysctl-permanent-baseline-v3"
LAST_APPLY_DIR="${BACKUP_DIR}/last_apply"
HISTORY_DIR="${BACKUP_DIR}/history"
LOG_FILE="/var/log/net-tune-pro-v3.log"

mkdir -p "$BACKUP_DIR" "$PERM_DIR" "$LAST_APPLY_DIR" "$HISTORY_DIR"
touch "$LOG_FILE"

CURRENT_PROFILE=""
ARCH="$(uname -m)"

# 版本号
VERSION="3.3.2-sui-hysteria2-auto-opt"

# ===================== 颜色 =====================
RED='\033[31m'; GREEN='\033[32m'; YELLOW='\033[33m'; BLUE='\033[36m'; BOLD='\033[1m'; NC='\033[0m'
ok(){ echo -e "${GREEN}✅ $*${NC}"; }
warn(){ echo -e "${YELLOW}⚠️  $*${NC}"; }
err(){ echo -e "${RED}❌ $*${NC}"; }
info(){ echo -e "${BLUE}ℹ️  $*${NC}"; }
line(){ echo "------------------------------------------------------------"; }

log(){ echo "[$(date '+%F %T')] $*" >> "$LOG_FILE"; }
pause(){ read -rp "按 Enter 继续..."; }
ts(){ date +%F_%H%M%S; }
cmd_exists(){ command -v "$1" >/dev/null 2>&1; }

need_root(){
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "请使用 root 运行：sudo bash /root/net-tune-pro-v3-zh.sh"
    exit 1
  fi
}

is_debian_like(){
  cmd_exists apt-get
}

# ===================== 依赖检查（尽量不强装） =====================
check_base_deps(){
  local miss=0
  for c in sysctl awk grep sed ip ss find mktemp install; do
    if ! cmd_exists "$c"; then
      err "缺少基础依赖：$c"
      miss=1
    fi
  done
  if (( miss == 1 )); then
    err "基础依赖不完整，请先安装后重试。"
    return 1
  fi
  return 0
}



ensure_mtr(){
  if cmd_exists mtr; then
    return 0
  fi

  info "未检测到 mtr，正在尝试自动安装..."
  if is_debian_like; then
    apt-get update -y >/dev/null 2>&1 || true
    if apt-get install -y mtr-tiny >/dev/null 2>&1 || apt-get install -y mtr >/dev/null 2>&1; then
      ok "mtr 安装成功"
      return 0
    fi
  elif cmd_exists yum; then
    if yum install -y mtr >/dev/null 2>&1; then
      ok "mtr 安装成功"
      return 0
    fi
  elif cmd_exists dnf; then
    if dnf install -y mtr >/dev/null 2>&1; then
      ok "mtr 安装成功"
      return 0
    fi
  fi

  err "mtr 自动安装失败，请手动安装后重试。"
  return 1
}

# ===================== 网络优化方案模板 =====================
common_base() {
cat <<'CONF'
# ===== Generated by net-tune-pro-v3-zh.sh =====
# 通用基础项
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 20
net.ipv4.ip_local_port_range = 10240 65535
net.ipv4.tcp_slow_start_after_idle = 0
CONF
}
profile_balanced(){ cat <<'CONF'
# ---- 方案：平衡版 ----
net.core.netdev_max_backlog = 65536
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_aggressive(){ cat <<'CONF'
# ---- 方案：激进版 ----
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_fin_timeout = 15
CONF
}
profile_aggressive_safe(){ cat <<'CONF'
# ---- 方案：激进稳妥版 ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_udp_quic(){
    echo "# ---- 方案：UDP 专项（s-ui 面板 Hysteria2 生产极致版）----"

    # 自动内存检测（s-ui Hysteria2 专用，低配绝不 OOM）
    TOTAL_MEM=$(free -m 2>/dev/null | awk '/^Mem:/{print $2}')
    TOTAL_MEM=${TOTAL_MEM:-0}
    if [ "$TOTAL_MEM" -ge 16384 ]; then
        RMAX=134217728      # 128MB（16G+ 高端机）
        echo "# 检测到 ≥16G 内存 → 128MB缓冲"
    elif [ "$TOTAL_MEM" -ge 8192 ]; then
        RMAX=67108864       # 64MB（8G+ 推荐）
        echo "# 检测到 ≥8G 内存 → 64MB缓冲"
    elif [ "$TOTAL_MEM" -ge 4096 ]; then
        RMAX=33554432       # 32MB（4G+ 安全）
        echo "# 检测到 ≥4G 内存 → 32MB缓冲"
    else
        RMAX=16777216       # 16MB（低配极简）
        echo "# 检测到低内存 → 16MB缓冲"
    fi

    # UDP 内存三元组按实际物理内存动态计算（单位：页=4KB）
    local TOTAL_PAGES=$(( TOTAL_MEM * 256 ))  # MB → 页(4KB)
    local UDP_MIN=$(( TOTAL_PAGES / 4 ))
    local UDP_PRESSURE=$(( TOTAL_PAGES / 3 ))
    local UDP_MAX=$(( TOTAL_PAGES / 2 ))
    # 设置合理下限，避免极低配机器值过小
    [ "$UDP_MIN" -lt 65536 ] && UDP_MIN=65536
    [ "$UDP_PRESSURE" -lt 131072 ] && UDP_PRESSURE=131072
    [ "$UDP_MAX" -lt 262144 ] && UDP_MAX=262144

cat <<CONF
# UDP专项 - s-ui Hysteria2 生产极致配置（全线路通用优化）
net.core.rmem_default = 262144
net.core.rmem_max = $((RMAX * 2))
net.core.wmem_default = 262144
net.core.wmem_max = $((RMAX * 2))

# TCP 必然共存：s-ui 面板/DNS/伪装站
net.ipv4.tcp_rmem = 4096 87380 $RMAX
net.ipv4.tcp_wmem = 4096 65536 $RMAX

# UDP专属关键参数（QUIC 带宽利用率核心，按实际内存动态计算）
net.ipv4.udp_mem = $UDP_MIN $UDP_PRESSURE $UDP_MAX
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384

# s-ui 高并发优化（QUIC高PPS特性）
net.core.netdev_max_backlog = 65536
net.core.somaxconn = 8192
net.ipv4.tcp_max_syn_backlog = 8192
net.core.optmem_max = 262144

# 端口复用 + 快速回收（Hysteria2 短连接密集）
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_notsent_lowat = 16384

# ---- 非GIA线路 UDP 增强（普通CN2/联通/移动直连等高丢包线路）----
# ECN 显式拥塞通知：避免丢包式拥塞感知，QUIC/TCP 均受益
net.ipv4.tcp_ecn = 1
# SACK 选择性确认 + 时间戳：高丢包环境下精准重传
net.ipv4.tcp_sack = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_window_scaling = 1
# 快速重传：TLP（尾丢探测）+ 早期重传，减少 RTO 等待
net.ipv4.tcp_early_retrans = 3
# 乱序容忍：非GIA线路包乱序概率高，避免误判为丢包
net.ipv4.tcp_reordering = 6
# RACK 丢包检测：替代传统 dupack，对乱序+丢包场景更精准
net.ipv4.tcp_recovery = 1

# ---- 晚高峰自适应增强 ----
# 加大软中断预算：高峰期包量暴增时内核有足够处理时间
net.core.netdev_budget = 1200
net.core.netdev_budget_usecs = 25000
# 连接快速回收：高峰期 TIME_WAIT 堆积会耗尽端口
net.ipv4.tcp_max_tw_buckets = 65536
# 孤儿连接上限：防止半关闭连接占满内存
net.ipv4.tcp_max_orphans = 32768
CONF
}
profile_low_1c1g(){ cat <<'CONF'
# ---- 方案：低内存保守版 1C/1G ----
net.core.netdev_max_backlog = 8192
net.core.somaxconn = 2048
net.ipv4.tcp_max_syn_backlog = 8192
net.core.rmem_default = 131072
net.core.wmem_default = 131072
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65536 8388608
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}
profile_low_2c2g(){ cat <<'CONF'
# ---- 方案：低内存保守版 2C/2G ----
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 16384
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
CONF
}
profile_bw_1g(){ cat <<'CONF'
# ---- 方案：高带宽版 1G口 ----
net.core.netdev_max_backlog = 32768
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 65536
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_bw_10g(){ cat <<'CONF'
# ---- 方案：高带宽版 10G口 ----
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
CONF
}
profile_vps_max(){ cat <<'CONF'
# ---- 方案：VPS 极致带宽版（虚拟网卡） ----
# 针对虚拟化环境优化，最大化带宽利用率
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 524288
net.core.wmem_default = 524288
net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.ipv4.tcp_rmem = 4096 131072 134217728
net.ipv4.tcp_wmem = 4096 131072 134217728
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
CONF
}

profile_peak_jitter(){ cat <<'CONF'
# ---- 方案：晚高峰抗抖动版 (Anti-Bufferbloat) ----
# 针对晚高峰丢包严重/延迟抖动场景
# 核心策略：大幅减小缓冲区，避免 Bufferbloat，牺牲极限吞吐换取稳定性
# BDP (100Mbps, 200ms) ~= 2.5MB. 设置 8MB 也就是足够 300Mbps+
net.core.netdev_max_backlog = 8192
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 8192
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 8388608
net.core.wmem_max = 8388608
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65536 8388608
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
CONF
}

profile_streaming(){ cat <<'CONF'
# ---- 方案：流媒体代理版（VLESS/Reality TCP 优化） ----
# 针对 Netflix/YouTube/TikTok 等视频流媒体场景
# 基于激进稳妥版缓冲区 + 流媒体专用 TCP 选项
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 32768
net.ipv4.tcp_max_syn_backlog = 131072
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_thin_linear_timeouts = 1
CONF
}

profile_http_proxy(){ cat <<'CONF'
# ---- 方案：HTTP 代理专项版（高并发 TCP 代理优化） ----
# 针对 Squid/Nginx/HAProxy/Clash 等 HTTP(S) 代理场景
# 特点：高连接数、短连接周转快、TIME_WAIT 回收、低延迟响应
net.core.netdev_max_backlog = 131072
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 262144
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
# HTTP 代理专用优化
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_max_tw_buckets = 65536
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.core.optmem_max = 65536
net.ipv4.tcp_max_orphans = 65536
CONF
}

emit_profile(){
  case "$1" in
    balanced) profile_balanced ;;
    aggressive) profile_aggressive ;;
    aggressive_safe) profile_aggressive_safe ;;
    udp_quic) profile_udp_quic ;;
    streaming) profile_streaming ;;
    http_proxy) profile_http_proxy ;;
    low_1c1g) profile_low_1c1g ;;
    low_2c2g) profile_low_2c2g ;;
    bw_1g) profile_bw_1g ;;
    bw_10g) profile_bw_10g ;;
    vps_max) profile_vps_max ;;
    peak_jitter) profile_peak_jitter ;;
    *) return 1 ;;
  esac
}

get_profile_name(){
  case "$1" in
    balanced) echo "平衡版（通用推荐）" ;;
    aggressive) echo "激进版（高并发/高PPS）" ;;
    aggressive_safe) echo "激进稳妥版（推荐）" ;;
    udp_quic) echo "UDP 专项版（s-ui Hysteria2 生产极致版）" ;;
    streaming) echo "流媒体代理版（VLESS/Reality TCP）" ;;
    http_proxy) echo "HTTP 代理专项版（Squid/Nginx/Clash）" ;;
    low_1c1g) echo "低内存保守版（1C/1G）" ;;
    low_2c2g) echo "低内存保守版（2C/2G）" ;;
    bw_1g) echo "高带宽版（1G口）" ;;
    bw_10g) echo "高带宽版（10G口）" ;;
    vps_max) echo "VPS 极致带宽版（虚拟网卡）" ;;
    peak_jitter) echo "晚高峰抗抖动版 (Anti-Bufferbloat)" ;;
    *) echo "未知方案 ($1)" ;;
  esac
}

# ===================== 校验/检查 =====================
extract_max_from_triplet(){ awk '{print $3}' <<<"$1"; }
escape_regex() { sed -e 's/[][(){}.^$*+?|\/]/\\&/g' <<<"$1"; }

validate_profile_semantics(){
  local tmp="$1"
  local rmem_max wmem_max tcp_rmem tcp_wmem tr tw
  rmem_max="$(awk -F= '/^[[:space:]]*net\.core\.rmem_max[[:space:]]*=/{gsub(/[ \t]/,"",$2);print $2}' "$tmp" | tail -n1)"
  wmem_max="$(awk -F= '/^[[:space:]]*net\.core\.wmem_max[[:space:]]*=/{gsub(/[ \t]/,"",$2);print $2}' "$tmp" | tail -n1)"
  tcp_rmem="$(awk -F= '/^[[:space:]]*net\.ipv4\.tcp_rmem[[:space:]]*=/{sub(/^[ \t]+/,"",$2);print $2}' "$tmp" | tail -n1)"
  tcp_wmem="$(awk -F= '/^[[:space:]]*net\.ipv4\.tcp_wmem[[:space:]]*=/{sub(/^[ \t]+/,"",$2);print $2}' "$tmp" | tail -n1)"
  tr="$(extract_max_from_triplet "$tcp_rmem")"
  tw="$(extract_max_from_triplet "$tcp_wmem")"
  [[ -n "$rmem_max" && -n "$tr" ]] && (( rmem_max < tr )) && { err "参数校验失败：rmem_max < tcp_rmem 最大值"; return 1; }
  [[ -n "$wmem_max" && -n "$tw" ]] && (( wmem_max < tw )) && { err "参数校验失败：wmem_max < tcp_wmem 最大值"; return 1; }
  
  # [NEW] 硬件限制检测与调整
  local total_mem_kb
  total_mem_kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
  
  # 简单策略：单 Socket 最大缓冲区不应超过物理内存的 1/4 (避免 OOM)
  local max_allowed_kb=$(( total_mem_kb / 4 ))
  local rmem_max_kb=$(( rmem_max / 1024 ))
  local wmem_max_kb=$(( wmem_max / 1024 ))
  
  if (( total_mem_kb > 0 )); then
    if (( rmem_max_kb > max_allowed_kb )); then
        warn "检测到 rmem_max ($((rmem_max/1024/1024))MB) 超过系统建议值 ($((max_allowed_kb/1024))MB)"
        info "已自动调整 rmem_max 为安全值..."
        sed -i "s/^net.core.rmem_max.*/net.core.rmem_max = $((max_allowed_kb * 1024))/" "$tmp"
        # 同时尝试调整 tcp_* 最大值（如果预置方案包含）
        if grep -q "^net\.ipv4\.tcp_rmem" "$tmp"; then
            sed -i "s/^net.ipv4.tcp_rmem.*/net.ipv4.tcp_rmem = 4096 87380 $((max_allowed_kb * 1024))/" "$tmp"
        fi
    fi
    if (( wmem_max_kb > max_allowed_kb )); then
        warn "检测到 wmem_max ($((wmem_max/1024/1024))MB) 超过系统建议值 ($((max_allowed_kb/1024))MB)"
        info "已自动调整 wmem_max 为安全值..."
        sed -i "s/^net.core.wmem_max.*/net.core.wmem_max = $((max_allowed_kb * 1024))/" "$tmp"
        # 同时尝试调整 tcp_* 最大值（如果预置方案包含）
        if grep -q "^net\.ipv4\.tcp_wmem" "$tmp"; then
            sed -i "s/^net.ipv4.tcp_wmem.*/net.ipv4.tcp_wmem = 4096 65536 $((max_allowed_kb * 1024))/" "$tmp"
        fi
    fi
  fi

  return 0
}

precheck(){
  echo
  echo -e "${BOLD}【预检查阶段】${NC}"
  line
  check_base_deps || return 1

  # ===== 内核与拥塞控制状态 =====
  local kernel_ver current_cc current_qdisc
  kernel_ver="$(uname -r || true)"
  info "内核版本：$kernel_ver"
  
  if [[ -r /proc/sys/net/ipv4/tcp_available_congestion_control ]]; then
    local available_cc
    available_cc="$(cat /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null || true)"
    info "可用拥塞控制：$available_cc"
  fi
  
  # 当前拥塞控制状态
  current_cc="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  current_qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  info "当前拥塞控制：$current_cc"
  info "当前队列算法：$current_qdisc"

  # ===== 虚拟化类型检测 =====
  local virt_type
  virt_type=""
  if cmd_exists systemd-detect-virt; then
    virt_type="$(systemd-detect-virt 2>/dev/null || true)"
  elif [[ -r /sys/hypervisor/type ]]; then
    virt_type="$(cat /sys/hypervisor/type 2>/dev/null || true)"
  elif grep -qi "docker\|lxc" /proc/1/cgroup 2>/dev/null; then
    virt_type="container"
  fi
  
  if [[ -n "$virt_type" && "$virt_type" != "none" ]]; then
    case "$virt_type" in
      kvm)       info "虚拟化类型：KVM（支持自定义内核）" ;;
      qemu)      info "虚拟化类型：QEMU（支持自定义内核）" ;;
      xen)       info "虚拟化类型：Xen（支持自定义内核）" ;;
      vmware)    info "虚拟化类型：VMware（支持自定义内核）" ;;
      microsoft) info "虚拟化类型：Hyper-V（支持自定义内核）" ;;
      openvz)    warn "虚拟化类型：OpenVZ（⚠️ 无法更换内核）" ;;
      lxc|lxc-libvirt) warn "虚拟化类型：LXC 容器（⚠️ 无法更换内核）" ;;
      container|docker) warn "虚拟化类型：容器环境（⚠️ 无法更换内核）" ;;
      *) info "虚拟化类型：$virt_type" ;;
    esac
  else
    info "虚拟化类型：物理机或未检测到"
  fi

  # ===== CPU 性能检测 =====
  local cpu_model cpu_cores
  cpu_model="$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || echo unknown)"
  cpu_cores="$(nproc 2>/dev/null || echo 1)"
  info "CPU：$cpu_model（${cpu_cores}核）"
  
  # AES-NI 指令集检测（加密性能关键）
  if grep -qw aes /proc/cpuinfo 2>/dev/null; then
    ok "AES-NI：已支持（加密性能优秀）"
  else
    warn "AES-NI：未检测到（加密性能可能较低，建议使用 ChaCha20）"
  fi

  # ===== 网卡检测 =====
  local nic speed driver ethtool_speed bw_hint
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  if [[ -n "${nic:-}" ]]; then
    info "默认网卡：$nic"
    
    # 获取驱动类型
    driver=""
    if [[ -r "/sys/class/net/$nic/device/driver" ]]; then
      driver="$(basename "$(readlink -f "/sys/class/net/$nic/device/driver")" 2>/dev/null || true)"
    elif [[ -r "/sys/class/net/$nic/device/uevent" ]]; then
      driver="$(awk -F= '/^DRIVER=/{print $2}' "/sys/class/net/$nic/device/uevent" 2>/dev/null || true)"
    fi
    
    # 尝试从 /sys 读取速度
    speed=""
    if [[ -r "/sys/class/net/$nic/speed" ]]; then
      speed="$(cat "/sys/class/net/$nic/speed" 2>/dev/null || true)"
    fi
    
    # 如果 /sys 返回 -1，尝试 ethtool
    ethtool_speed=""
    if [[ "$speed" == "-1" || -z "$speed" ]] && cmd_exists ethtool; then
      ethtool_speed="$(ethtool "$nic" 2>/dev/null | awk '/Speed:/ {print $2}' || true)"
      if [[ -n "$ethtool_speed" && "$ethtool_speed" != "Unknown!" ]]; then
        speed="$ethtool_speed"
      fi
    fi
    
    # 根据驱动类型推断带宽
    bw_hint=""
    case "${driver:-unknown}" in
      virtio_net|virtio-pci)
        bw_hint="10Gbps+（KVM/QEMU 虚拟化，实际取决于主机商限制）"
        ;;
      xen_netfront)
        bw_hint="取决于实例类型（Xen/AWS EC2 旧实例）"
        ;;
      ena)
        bw_hint="最高 100Gbps（AWS ENA 增强网络）"
        ;;
      hv_netvsc)
        bw_hint="取决于实例类型（Hyper-V/Azure）"
        ;;
      vmxnet3)
        bw_hint="10Gbps（VMware 虚拟化）"
        ;;
      veth)
        bw_hint="容器网络（Docker/LXC），带宽由主机决定"
        ;;
      *)
        bw_hint=""
        ;;
    esac
    
    # 输出检测结果
    if [[ -n "$driver" ]]; then
      info "网卡驱动：$driver"
    fi
    
    if [[ -n "$speed" && "$speed" != "-1" && "$speed" != "Unknown!" ]]; then
      info "网卡速率：${speed}Mbps"
    elif [[ -n "$bw_hint" ]]; then
      info "推测带宽上限：$bw_hint"
      echo -e "  ${YELLOW}💡 建议：选择「VPS 极致带宽版（虚拟网卡）」方案以最大化利用带宽${NC}"
    else
      info "网卡速率：虚拟网卡（无法检测物理链路速度）"
    fi
  fi

  # ===== UDP 端口检测 =====
  line
  info "正在检测 UDP 连通性..."
  local udp_test_result
  # 检查是否有 UDP 相关的 iptables 规则阻止
  if cmd_exists iptables; then
    local udp_drop_rules
    udp_drop_rules="$(iptables -L -n 2>/dev/null | grep -i "udp.*drop\|drop.*udp" | head -3 || true)"
    if [[ -n "$udp_drop_rules" ]]; then
      warn "检测到 UDP 丢弃规则（可能影响 Hysteria2 等 UDP 代理）："
      echo "$udp_drop_rules" | head -3 || true
    else
      ok "未检测到 UDP 阻止规则"
    fi
  fi

  # ===== 端口限速检测（tc qdisc） =====
  if cmd_exists tc && [[ -n "${nic:-}" ]]; then
    local tc_rules
    tc_rules="$(tc qdisc show dev "$nic" 2>/dev/null || true)"
    if echo "$tc_rules" | grep -qiE "tbf|htb|cake|police"; then
      warn "检测到流量整形规则（可能存在端口限速）："
      echo "$tc_rules" | grep -iE "tbf|htb|cake|police" | head -3 || true
    else
      ok "未检测到端口限速规则"
    fi
  fi

  # ===== 网络配置总览 =====
  line
  echo -e "${BOLD}=== 网卡信息 ===${NC}"
  ip link show 2>/dev/null | grep -E "^[0-9]+: " || true
  echo

  echo -e "${BOLD}=== TCP 拥塞控制 ===${NC}"
  sysctl net.ipv4.tcp_congestion_control 2>/dev/null || echo "  无法读取"
  echo

  echo -e "${BOLD}=== 默认队列调度器 ===${NC}"
  sysctl net.core.default_qdisc 2>/dev/null || echo "  无法读取"
  echo

  echo -e "${BOLD}=== TCP backlog 和最大连接数 ===${NC}"
  sysctl net.core.netdev_max_backlog net.core.somaxconn 2>/dev/null || true
  echo

  echo -e "${BOLD}=== TCP 缓冲区设置 ===${NC}"
  sysctl net.ipv4.tcp_rmem net.ipv4.tcp_wmem net.core.rmem_max net.core.wmem_max 2>/dev/null || true
  echo

  echo -e "${BOLD}=== 网卡队列长度 (txqueuelen) ===${NC}"
  local iface_dir
  for iface_dir in /sys/class/net/*; do
    local iface_name
    iface_name="$(basename "$iface_dir")"
    [[ "$iface_name" == "lo" ]] && continue
    echo -n "  $iface_name: "
    cat "$iface_dir/tx_queue_len" 2>/dev/null || echo "无法读取"
  done
  echo

  echo -e "${BOLD}=== BBR 模块加载情况 ===${NC}"
  if lsmod 2>/dev/null | grep -q bbr; then
    ok "BBR 已加载"
  else
    warn "BBR 未加载"
  fi
  echo

  echo -e "${BOLD}=== 适合代理建议 ===${NC}"
  echo -e "  ${GREEN}推荐配置: BBR + fq + txqueuelen>=8192 + netdev_max_backlog>=16384${NC}"
  echo "  查看上面各项是否满足判断即可"

  line
  [[ -w /etc/sysctl.d ]] || { err "/etc/sysctl.d 不可写"; return 1; }
  sysctl -a >/dev/null 2>&1 || { err "sysctl 读取失败"; return 1; }

  ok "预检查通过"
  return 0
}

conflict_check(){
  echo
  echo -e "${BOLD}【冲突检测】sysctl 重复键${NC}"
  line
  local files=()
  [[ -f /etc/sysctl.conf ]] && files+=(/etc/sysctl.conf)
  while IFS= read -r -d '' f; do files+=("$f"); done < <(find /etc/sysctl.d -maxdepth 1 -type f -name "*.conf" -print0 2>/dev/null | sort -z)
  [[ ${#files[@]} -eq 0 ]] && { warn "未找到配置文件"; return 0; }

  local out
  out="$(
    awk '
      function trim(s){gsub(/^[ \t]+|[ \t]+$/,"",s); return s}
      {
        line=$0; sub(/#.*/,"",line)
        if (line ~ /^[ \t]*$/ || line !~ /=/) next
        split(line,a,"="); key=trim(a[1]); if(key=="") next
        kf=key SUBSEP FILENAME
        if (!(kf in seen)) { seen[kf]=1; cnt[key]++; files[key]=files[key]?files[key] "," FILENAME:FILENAME }
      }
      END{ for(k in cnt) if(cnt[k]>1) print k " => " files[k] }
    ' "${files[@]}" | sort
  )"

  if [[ -z "$out" ]]; then
    ok "未发现重复键冲突"
  else
    warn "发现重复键："
    echo "$out"
    echo
    read -rp "是否尝试自动修复（注释掉非管理文件中的冗余项）？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      resolve_conflicts "$out"
    fi
  fi
  line
}

resolve_conflicts(){
  local conflict_out="$1"
  [[ -z "$conflict_out" ]] && return 0

  local hdir
  hdir="$(save_last_and_history_snapshot)"
  info "修复前快照：$hdir"

  info "正在准备修复冲突..."
  local key file_list f
  while IFS= read -r row; do
    [[ -z "$row" ]] && continue
    key="${row%% => *}"
    file_list="${row#* => }"
    
    IFS=',' read -ra file_array <<< "$file_list"
    for f in "${file_array[@]}"; do
      # 排除脚本管理的文件
      if [[ "$f" == "$ACTIVE_FILE" ]]; then
        continue
      fi
      
      # 全量转义正则特殊字符
      local escaped_key
      escaped_key="$(escape_regex "$key")"

      if grep -qiE "^[[:space:]]*${escaped_key}[[:space:]]*=" "$f"; then
        if ! grep -q "commented by net-tune-pro repair" "$f"; then
          info "在 $f 中注释掉冲突键：$key"
          sed -i -E "s/^([[:space:]]*${escaped_key}[[:space:]]*=.*)$/# \1 # commented by net-tune-pro repair/" "$f"
        fi
      fi
    done
  done <<< "$conflict_out"
  
  ok "自动修复尝试完成。建议再次运行冲突检测。"
}

# ===================== 快照/回滚/永久基线 =====================
save_last_and_history_snapshot(){
  local stamp hdir
  stamp="$(ts)"
  rm -rf "${LAST_APPLY_DIR:?}/"* 2>/dev/null || true
  mkdir -p "$LAST_APPLY_DIR/sysctl.d"
  hdir="${HISTORY_DIR}/${stamp}"
  mkdir -p "$hdir/sysctl.d"

  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$LAST_APPLY_DIR/sysctl.conf" || true
  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$hdir/sysctl.conf" || true
  cp -a /etc/sysctl.d/*.conf "$LAST_APPLY_DIR/sysctl.d/" 2>/dev/null || true
  cp -a /etc/sysctl.d/*.conf "$hdir/sysctl.d/" 2>/dev/null || true

  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$LAST_APPLY_DIR/managed-active.conf" || true
  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$hdir/managed-active.conf" || true


  sysctl -a 2>/dev/null > "$LAST_APPLY_DIR/runtime-sysctl-all.txt" || true
  sysctl -a 2>/dev/null > "$hdir/runtime-sysctl-all.txt" || true
  echo "$hdir"
}

clean_old_snapshots(){
  local keep_count="${1:-20}"
  local snapshots count to_delete
  snapshots=($(ls -1d "${HISTORY_DIR}/"* 2>/dev/null | sort))
  count=${#snapshots[@]}
  
  if (( count <= keep_count )); then
    info "当前快照数量：$count（保留阈值：$keep_count），无需清理"
    return 0
  fi
  
  to_delete=$((count - keep_count))
  info "将清理 $to_delete 个旧快照，保留最近 $keep_count 个"
  
  for ((i=0; i<to_delete; i++)); do
    rm -rf "${snapshots[$i]}"
    info "已删除：${snapshots[$i]}"
  done
  
  ok "清理完成，当前剩余：$keep_count 个快照"
}

rollback_last_apply_point(){
  if [[ -f "$LAST_APPLY_DIR/managed-active.conf" ]]; then
    cp -a "$LAST_APPLY_DIR/managed-active.conf" "$ACTIVE_FILE"
  else
    rm -f "$ACTIVE_FILE"
  fi


  if sysctl --system >/tmp/net-tune-v3-rollback.log 2>&1; then
    ok "已回滚到上一次应用点（仅管理文件）"
  else
    err "回滚失败，日志：/tmp/net-tune-v3-rollback.log"
    return 1
  fi
}

save_permanent_baseline(){
  local marker="${PERM_DIR}/BASELINE_LOCK"
  [[ -f "$marker" ]] && { warn "永久初始备份已存在：$PERM_DIR"; return 0; }

  mkdir -p "$PERM_DIR/sysctl.d"
  [[ -f /etc/sysctl.conf ]] && cp -a /etc/sysctl.conf "$PERM_DIR/sysctl.conf" || true
  cp -a /etc/sysctl.d/*.conf "$PERM_DIR/sysctl.d/" 2>/dev/null || true
  [[ -f "$ACTIVE_FILE" ]] && cp -a "$ACTIVE_FILE" "$PERM_DIR/managed-active.conf" || true


  # 注意：heredoc 未加引号，变量会在写入时展开（记录创建时信息）
  cat > "$marker" <<LOCK
CreatedAt=$(date '+%F %T')
Host=$(hostname)
Kernel=$(uname -r)
Note=Permanent baseline, do not overwrite automatically.
LOCK
  chmod 700 "$PERM_DIR" || true
  chmod 600 "$marker" || true
  ok "永久初始备份创建完成：$PERM_DIR"

  if cmd_exists chattr; then
    read -rp "是否给 BASELINE_LOCK 添加不可变属性（chattr +i）？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      if chattr +i "$marker" 2>/dev/null; then
        ok "已加锁"
      else
        warn "chattr +i 失败（文件系统可能不支持）"
      fi
    fi
  fi
}

restore_permanent_baseline(){
  local marker="${PERM_DIR}/BASELINE_LOCK"
  [[ -f "$marker" ]] || { err "未找到永久初始备份"; return 1; }

  save_last_and_history_snapshot >/dev/null || true
  if [[ -f "$PERM_DIR/managed-active.conf" ]]; then
    cp -a "$PERM_DIR/managed-active.conf" "$ACTIVE_FILE"
  else
    rm -f "$ACTIVE_FILE"
  fi


  if sysctl --system >/tmp/net-tune-v3-restore-baseline.log 2>&1; then
    ok "已回滚到永久初始配置（管理文件范围）"
  else
    err "回滚失败，日志：/tmp/net-tune-v3-restore-baseline.log"
    return 1
  fi
}

# ===================== 网络方案应用（原子写入） =====================
render_profile_to_tmp(){
  local p="$1" tmp="$2"
  { common_base; emit_profile "$p"; } > "$tmp"
}

apply_profile(){
  local p="$1" tmp hdir
  tmp="$(mktemp /tmp/net-tune-v3.XXXXXX.conf)"
  render_profile_to_tmp "$p" "$tmp" || { rm -f "$tmp"; err "未知方案"; return 1; }
  validate_profile_semantics "$tmp" || { rm -f "$tmp"; return 1; }

  hdir="$(save_last_and_history_snapshot)"
  info "快照已保存：$hdir"

  install -m 0644 "$tmp" "${ACTIVE_FILE}.new"
  mv -f "${ACTIVE_FILE}.new" "$ACTIVE_FILE"
  rm -f "$tmp"

  if ! sysctl -p "$ACTIVE_FILE" >/tmp/net-tune-v3-apply-single.log 2>&1; then
    err "单文件校验失败：/tmp/net-tune-v3-apply-single.log"
    rollback_last_apply_point >/dev/null 2>&1 || true
    return 1
  fi
  if ! sysctl --system >/tmp/net-tune-v3-apply.log 2>&1; then
    err "全量加载失败（可能外部冲突）：/tmp/net-tune-v3-apply.log"
    rollback_last_apply_point >/dev/null 2>&1 || true
    return 1
  fi

  CURRENT_PROFILE="$p"
  echo "$p" > "$PROFILE_STATE_FILE"
  ok "方案已应用：$p"
  log "APPLY profile=$p success"

  # === s-ui 面板专用优化（仅 UDP 专项版触发）===
  if [[ "$p" == "udp_quic" ]] && systemctl is-active s-ui.service >/dev/null 2>&1; then
      mkdir -p /etc/systemd/system/s-ui.service.d
      cat > /etc/systemd/system/s-ui.service.d/udp-priority.conf << EOF
[Service]
CPUSchedulingPolicy=other
Nice=-10
IOSchedulingClass=best-effort
IOSchedulingPriority=0
LimitNOFILE=524288
LimitNPROC=65536
EOF
      systemctl daemon-reload
      systemctl restart s-ui.service
      ok "s-ui.service 已优化：Nice=-10 + 文件描述符 524288"
  elif [[ "$p" == "udp_quic" ]]; then
      warn "未检测到 s-ui.service，请手动确认服务状态"
  fi

}

mtr_probe_target(){
  local ip="$1"
  local report_line loss avg stdev

  report_line="$(mtr -r -c 10 -n "$ip" 2>/dev/null | awk '/^[[:space:]]*[0-9]+\./{line=$0} END{print line}')"
  if [[ -z "$report_line" ]]; then
    return 1
  fi

  # mtr 报告常见列：Loss% Snt Last Avg Best Wrst StDev
  # 这里输出：loss avg jitter(stdev)
  read -r loss avg stdev < <(echo "$report_line" | awk '{
    l=$3; gsub(/%/,"",l);
    a=$5;
    j=$9;
    if (l ~ /^[0-9.]+$/ && a ~ /^[0-9.]+$/ && j ~ /^[0-9.]+$/) {
      printf "%s %s %s\n", l, a, j;
    }
  }')

  if [[ -z "${loss:-}" || -z "${avg:-}" || -z "${stdev:-}" ]]; then
    return 1
  fi

  echo "$loss $avg $stdev"
}

auto_optimize(){
  echo
  echo -e "${BOLD}【智能检测与自动优化（HY2/VPS）】${NC}"
  line

  local total_mem_mb cpu_cores
  total_mem_mb="$(free -m | awk '/^Mem:/{print $2}' 2>/dev/null || echo 0)"
  cpu_cores="$(nproc 2>/dev/null || echo 1)"
  info "内存：${total_mem_mb} MB"
  info "CPU 核数：${cpu_cores}"

  ensure_mtr || return 1

  # 线路测试点：阿里DNS、114DNS、中国移动骨干（安徽）
  local test_ips=("223.5.5.5" "114.114.114.114" "112.28.209.196")
  local count=0
  local sum_rtt="0" sum_jitter="0" sum_loss="0"

  for ip in "${test_ips[@]}"; do
    local result loss avg jitter
    info "mtr 测试目标：$ip"
    result="$(mtr_probe_target "$ip" || true)"
    if [[ -z "$result" ]]; then
      warn "mtr 解析失败：$ip（已跳过）"
      continue
    fi

    read -r loss avg jitter <<< "$result"
    info "结果：RTT(avg)=${avg}ms, jitter(stdev)=${jitter}ms, loss=${loss}%"

    sum_rtt="$(awk -v a="$sum_rtt" -v b="$avg" 'BEGIN{printf "%.3f", a+b}')"
    sum_jitter="$(awk -v a="$sum_jitter" -v b="$jitter" 'BEGIN{printf "%.3f", a+b}')"
    sum_loss="$(awk -v a="$sum_loss" -v b="$loss" 'BEGIN{printf "%.3f", a+b}')"
    count=$((count + 1))
  done

  local avg_rtt avg_jitter avg_loss
  if (( count > 0 )); then
    avg_rtt="$(awk -v s="$sum_rtt" -v c="$count" 'BEGIN{printf "%.2f", s/c}')"
    avg_jitter="$(awk -v s="$sum_jitter" -v c="$count" 'BEGIN{printf "%.2f", s/c}')"
    avg_loss="$(awk -v s="$sum_loss" -v c="$count" 'BEGIN{printf "%.2f", s/c}')"
  else
    warn "mtr 测试全部失败，按普通高延迟线路处理"
    avg_rtt="200.00"
    avg_jitter="30.00"
    avg_loss="2.00"
  fi

  info "线路均值：RTT=${avg_rtt}ms, jitter=${avg_jitter}ms, loss=${avg_loss}%"

  local selected_profile="udp_quic"
  local reason="默认 HY2 UDP 专项"

  if (( total_mem_mb < 2048 || cpu_cores < 2 )); then
    selected_profile="low_1c1g"
    reason="资源较低（<2GB 或 <2核）"
  elif (( total_mem_mb < 4096 )); then
    selected_profile="low_2c2g"
    reason="内存低于 4GB"
  elif awk -v r="$avg_rtt" -v j="$avg_jitter" -v l="$avg_loss" 'BEGIN{exit !((r>150) || (j>20) || (l>1.0))}'; then
    selected_profile="peak_jitter"
    reason="线路高延迟/高抖动/有丢包"
  fi

  warn "推荐方案：$(get_profile_name "$selected_profile")（原因：$reason）"
  read -rp "是否立即应用该方案？[Y/n]: " yn
  if [[ -n "${yn:-}" && ! "${yn}" =~ ^[Yy]$ ]]; then
    warn "已取消应用"
    return 0
  fi

  precheck || return 1
  conflict_check
  apply_profile "$selected_profile" || return 1

  ok "智能优化完成：已应用 $(get_profile_name "$selected_profile")"
}


# ===================== 状态/监控 =====================
show_status(){
  echo
  echo -e "${BOLD}【当前状态】${NC}"
  line
  echo "网络方案托管文件：$ACTIVE_FILE"
  echo "当前会话方案    ：${CURRENT_PROFILE:-unknown}"
  line
  [[ -f "$ACTIVE_FILE" ]] && { echo "[网络方案文件内容]"; cat "$ACTIVE_FILE"; line; }

  sysctl \
    net.core.default_qdisc \
    net.ipv4.tcp_congestion_control \
    net.core.netdev_max_backlog \
    net.core.somaxconn \
    net.ipv4.tcp_max_syn_backlog \
    net.core.rmem_max \
    net.core.wmem_max \
    net.ipv4.tcp_rmem \
    net.ipv4.tcp_wmem 2>/dev/null || true
}

watch_metrics(){
  info "实时监控中（Ctrl+C 返回）"
  sleep 1
  while true; do
    clear
    echo -e "${BOLD}===== $(date '+%F %T') =====${NC}"
    echo "[softnet_stat 丢包列（第2列）前8行]"
    awk '{print NR ": " $2}' /proc/net/softnet_stat 2>/dev/null | head -n 8 || true
    echo
    echo "[ss -s]"
    ss -s || true
    echo
    nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
    echo "[默认网卡统计: ${nic:-unknown}]"
    [[ -n "${nic:-}" ]] && ip -s link show "$nic" || ip -s link | sed -n '1,40p'
    echo
    echo "[内存]"
    free -h || true
    sleep 2
  done
}

# ===================== 系统级深度优化（Virtio/GRO） =====================
apply_system_optimizations(){
  echo
  echo -e "${BOLD}【系统级深度优化（网卡/队列/中断）】${NC}"
  line

  local nic driver
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  if [[ -z "${nic:-}" ]]; then
    err "未检测到默认网卡"
    return 1
  fi
  info "默认网卡：$nic"

  # 检测驱动类型
  driver=""
  if [[ -r "/sys/class/net/$nic/device/driver" ]]; then
    driver="$(basename "$(readlink -f "/sys/class/net/$nic/device/driver")" 2>/dev/null || true)"
  elif [[ -r "/sys/class/net/$nic/device/uevent" ]]; then
    driver="$(awk -F= '/^DRIVER=/{print $2}' "/sys/class/net/$nic/device/uevent" 2>/dev/null || true)"
  fi
  info "网卡驱动：${driver:-unknown}"

  if [[ "${driver:-}" != "virtio_net" && "${driver:-}" != "virtio-pci" ]]; then
    warn "当前网卡驱动不是 virtio_net，部分优化可能不适用"
    read -rp "是否继续？[y/N]: " yn
    if [[ ! "${yn:-N}" =~ ^[Yy]$ ]]; then
      return 0
    fi
  fi

  local cpu_count
  cpu_count="$(nproc 2>/dev/null || echo 1)"
  info "CPU 核心数：$cpu_count"

  # 自动安装 ethtool（多数优化依赖它）
  if ! cmd_exists ethtool; then
    warn "未检测到 ethtool，正在尝试自动安装..."
    if is_debian_like; then
      apt-get update -y >/dev/null 2>&1 || true
      apt-get install -y ethtool >/dev/null 2>&1 && ok "ethtool 安装成功" || warn "ethtool 安装失败，部分优化将跳过"
    elif cmd_exists yum; then
      yum install -y ethtool >/dev/null 2>&1 && ok "ethtool 安装成功" || warn "ethtool 安装失败，部分优化将跳过"
    else
      warn "无法自动安装 ethtool，请手动安装：apt install ethtool 或 yum install ethtool"
    fi
  fi

  line

  # ===== 1. Virtio 多队列 (Multiqueue) =====
  echo -e "${BOLD}[1/5] Virtio 多队列${NC}"
  if cmd_exists ethtool; then
    local max_combined current_combined
    max_combined="$(ethtool -l "$nic" 2>/dev/null | awk '/^Pre-set/,/^Current/{if(/Combined:/){print $2; exit}}')"
    current_combined="$(ethtool -l "$nic" 2>/dev/null | awk '/^Current/{flag=1} flag && /Combined:/{print $2; exit}')"
    if [[ -n "$max_combined" && "$max_combined" -gt 1 ]] 2>/dev/null; then
      local target=$((cpu_count < max_combined ? cpu_count : max_combined))
      if ethtool -L "$nic" combined "$target" 2>/dev/null; then
        ok "多队列已设置为 $target（最大 $max_combined）"
      else
        warn "多队列设置失败（当前：${current_combined:-unknown}）"
      fi
    else
      info "网卡不支持多队列或已是单队列"
    fi
  else
    warn "未安装 ethtool，跳过多队列设置"
  fi

  # ===== 2. RPS / RFS（软件级多核分发） =====
  echo -e "${BOLD}[2/5] RPS / RFS 多核分发${NC}"
  local rps_mask
  rps_mask="$(printf '%x' $(( (1 << cpu_count) - 1 )))"

  local rps_applied=0
  local queue_dir
  for queue_dir in /sys/class/net/"$nic"/queues/rx-*; do
    [[ -d "$queue_dir" ]] || continue
    if echo "$rps_mask" > "$queue_dir/rps_cpus" 2>/dev/null; then
      rps_applied=$((rps_applied + 1))
    fi
    if [[ -w "$queue_dir/rps_flow_cnt" ]]; then
      echo 4096 > "$queue_dir/rps_flow_cnt" 2>/dev/null || true
    fi
  done

  if [[ -w /proc/sys/net/core/rps_sock_flow_entries ]]; then
    echo 32768 > /proc/sys/net/core/rps_sock_flow_entries 2>/dev/null || true
  fi

  if (( rps_applied > 0 )); then
    ok "RPS 已应用到 $rps_applied 个接收队列（掩码：$rps_mask）"
    ok "RFS 已启用（flow_entries=32768，flow_cnt=4096）"
  else
    warn "RPS 设置失败（可能无权限）"
  fi

  # ===== 3. 网卡 Ring Buffer 加大 =====
  echo -e "${BOLD}[3/5] Ring Buffer${NC}"
  local max_rx="256" max_tx="256"
  if cmd_exists ethtool; then
    max_rx="$(ethtool -g "$nic" 2>/dev/null | awk '/^Pre-set/,/^Current/{if(/RX:/){print $2}}' | head -1 || true)"
    max_tx="$(ethtool -g "$nic" 2>/dev/null | awk '/^Pre-set/,/^Current/{if(/TX:/){print $2}}' | head -1 || true)"
    if [[ -n "$max_rx" && -n "$max_tx" ]]; then
      if ethtool -G "$nic" rx "$max_rx" tx "$max_tx" 2>/dev/null; then
        ok "Ring Buffer 已设为最大值（RX=$max_rx TX=$max_tx）"
      else
        info "Ring Buffer 设置失败或已是最大值"
      fi
    else
      info "Ring Buffer 信息读取失败，跳过"
    fi
  else
    warn "未安装 ethtool，跳过 Ring Buffer 设置"
  fi

  # ===== 4. 硬件卸载（GSO/GRO/TSO） =====
  echo -e "${BOLD}[4/5] 硬件卸载检查${NC}"
  if cmd_exists ethtool; then
    for feat in gso gro tso; do
      # ethtool -k 输出的是长名称，需要映射
      local long_feat=""
      case "$feat" in
        gso) long_feat="generic-segmentation-offload" ;;
        gro) long_feat="generic-receive-offload" ;;
        tso) long_feat="tcp-segmentation-offload" ;;
      esac

      local status
      # 使用 awk 提取状态，避免 grep 找不到时返回 1 导致脚本退出 (set -e)
      status="$(ethtool -k "$nic" 2>/dev/null | awk -v f="$long_feat" '$1 == f":" {print $2}')"
      
      if [[ "$status" == "off" ]]; then
        if ethtool -K "$nic" "$feat" on 2>/dev/null; then
          ok "$feat 已开启"
        else
          warn "$feat 开启失败（可能不支持）"
        fi
      else
        ok "$feat 已是开启状态"
      fi
    done
  else
    warn "未安装 ethtool，跳过硬件卸载检查"
  fi

  # ===== 5. 中断合并（减少 CPU 开销） =====
  echo -e "${BOLD}[5/5] 中断合并${NC}"
  if cmd_exists ethtool; then
    if ethtool -C "$nic" adaptive-rx on adaptive-tx on 2>/dev/null; then
      ok "自适应中断合并已开启"
    else
      info "自适应中断合并设置失败（virtio 可能不支持，这是正常的）"
    fi
  else
    warn "未安装 ethtool，跳过中断合并设置"
  fi

  line
  ok "系统级深度优化完成"

  if [[ "${1:-}" == "persist" ]]; then
    setup_persistence "$nic" "$cpu_count" "$rps_mask" "$max_rx" "$max_tx"
  else
    warn "当前为临时生效模式，重启后将失效"
  fi
}

set_txqueuelen(){
  echo
  echo -e "${BOLD}【设置网卡发送队列长度 (txqueuelen)】${NC}"
  line

  local nic current_len
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  [[ -z "$nic" ]] && nic="eth0"
  
  current_len="$(ip link show "$nic" 2>/dev/null | grep -oP 'txqueuelen \K\d+' || true)"
  info "当前网卡：$nic"
  info "当前队列长度：${current_len:-未知}"

  local new_len
  read -rp "请输入新的 txqueuelen 数值 (建议 5000-20000): " new_len
  if [[ ! "$new_len" =~ ^[0-9]+$ ]]; then
    err "输入无效，必须为数字"
    return 1
  fi

  if ip link set "$nic" txqueuelen "$new_len"; then
    ok "已成功设置 $nic 的 txqueuelen 为 $new_len"
  else
    err "修改失败，请检查权限或网卡名称"
    return 1
  fi

  read -rp "是否将此设置添加到开机自启 (rc.local)？[y/N]: " yn
  if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
    local rc_file="/etc/rc.local"
    # 确保 rc.local 存在
    if [[ ! -f "$rc_file" ]]; then
      printf '#!/bin/bash\nexit 0\n' > "$rc_file"
      chmod +x "$rc_file"
    fi
    # 移除旧的 txqueuelen 设置（如果有）
    sed -i "/ip link set .* txqueuelen/d" "$rc_file"
    # 在 exit 0 之前插入
    sed -i "/exit 0/i ip link set $nic txqueuelen $new_len" "$rc_file"
    ok "已添加到 /etc/rc.local"
  fi
}

setup_persistence(){
  local nic="$1" cpu_count="$2" rps_mask="$3" max_rx="${4:-256}" max_tx="${5:-256}"
  local rc_file="/etc/rc.local"
  
  info "正在配置开机自启..."

  # 确保 rc.local 存在并可执行
  if [[ ! -f "$rc_file" ]]; then
    printf '#!/bin/bash\nexit 0\n' > "$rc_file"
  fi
  chmod +x "$rc_file"

  # 清理旧的优化命令
  sed -i '/# Net-Tune-Pro-System-Optimize-Start/,/# Net-Tune-Pro-System-Optimize-End/d' "$rc_file"
  sed -i '/exit 0/d' "$rc_file"

  # 生成优化脚本片段
  local opt_block
  opt_block="# Net-Tune-Pro-System-Optimize-Start
# Generated by net-tune-pro at $(date)
nic=\"$nic\"
if [[ -d /sys/class/net/\$nic ]]; then
  # Multiqueue
  ethtool -L \$nic combined $cpu_count 2>/dev/null
  # Ring Buffer
  ethtool -G \$nic rx $max_rx tx $max_tx 2>/dev/null
  # Offload
  ethtool -K \$nic gso on gro on tso on 2>/dev/null
  # RPS
  for q in /sys/class/net/\$nic/queues/rx-*; do
    echo $rps_mask > \$q/rps_cpus 2>/dev/null
    echo 4096 > \$q/rps_flow_cnt 2>/dev/null
  done
  # RFS
  echo 32768 > /proc/sys/net/core/rps_sock_flow_entries 2>/dev/null

fi
# Net-Tune-Pro-System-Optimize-End"

  echo "$opt_block" >> "$rc_file"
  echo "exit 0" >> "$rc_file"
  
  ok "已添加到 /etc/rc.local，开机将自动应用优化"
  
  # 检查 rc-local 服务状态
  if systemctl is-active rc-local >/dev/null 2>&1 || systemctl is-enabled rc-local >/dev/null 2>&1; then
    :
  else
    warn "检测到 rc-local 服务未启用，尝试启用..."
    systemctl enable rc-local >/dev/null 2>&1 || true
    systemctl start rc-local >/dev/null 2>&1 || true
  fi
}

restore_system_optimizations(){
  echo
  echo -e "${BOLD}【还原系统默认配置】${NC}"
  line
  
  local nic
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  [[ -z "$nic" ]] && { err "未找到默认网卡"; return; }

  info "正在还原网卡 $nic 的配置..."

  # 清除 rc.local 中的持久化配置
  if [[ -f /etc/rc.local ]]; then
    sed -i '/# Net-Tune-Pro-System-Optimize-Start/,/# Net-Tune-Pro-System-Optimize-End/d' /etc/rc.local
    ok "已清除开机自启配置"
  fi

  # 还原 RPS (清零掩码)
  for q in /sys/class/net/"$nic"/queues/rx-*; do
    echo 0 > "$q/rps_cpus" 2>/dev/null || true
  done
  ok "已重置 RPS（恢复内核默认调度）"

  # RFS 全局表无法轻易还原默认值，通常重启即可，这里不强行改回 0 以免影响其他服务
  
  # 还原 ethtool 设置（通常需要知道原始值，这里只能尝试重置为保守值或提示重启）
  info "网卡硬件参数（多队列/Ring Buffer）建议重启服务器以完全恢复默认"
  
  line
  ok "还原操作完成，建议重启系统确保一切恢复初始状态"
}

# ===================== Swap 优化 =====================
optimize_swap(){
  echo
  echo -e "${BOLD}【Swap 优化】${NC}"
  line

  local total_mem_kb total_mem_mb swap_total_kb
  total_mem_kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
  total_mem_mb=$((total_mem_kb / 1024))
  swap_total_kb="$(awk '/^SwapTotal:/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"

  info "物理内存：${total_mem_mb} MB"
  info "当前 Swap 总量：$((swap_total_kb / 1024)) MB"

  local current_swappiness
  current_swappiness="$(sysctl -n vm.swappiness 2>/dev/null || echo 60)"
  info "当前 swappiness：$current_swappiness"

  if (( swap_total_kb == 0 )); then
    ok "当前系统未启用 Swap，无需操作"
    return 0
  fi

  local action=""
  if (( total_mem_mb > 1024 )); then
    # 大于 1G 内存：自动关闭 swap
    info "内存大于 1G，建议关闭 Swap 以提升性能"
    read -rp "确认关闭 Swap 并释放空间？[Y/n]: " yn
    if [[ "${yn:-Y}" =~ ^[Nn]$ ]]; then
      warn "已取消"
      return 0
    fi
    action="disable"
  else
    # 小于等于 1G 内存：让用户选择
    warn "内存 ≤ 1G，关闭 Swap 有 OOM 风险，请谨慎选择"
    echo
    echo "1) 关闭 Swap 并释放空间（激进，适合单一代理用途）"
    echo "2) 降低 swappiness 至 10（稳妥推荐）"
    echo "0) 取消"
    read -rp "请选择 [0-2]: " sc
    case "$sc" in
      1) action="disable" ;;
      2) action="lower" ;;
      0|*) warn "已取消"; return 0 ;;
    esac
  fi

  if [[ "$action" == "disable" ]]; then
    # ---- 关闭 Swap 并释放空间 ----
    info "正在关闭所有 Swap..."
    swapoff -a 2>/dev/null || { err "swapoff 失败"; return 1; }
    ok "Swap 已关闭"

    # 删除 swap 文件（常见路径）
    local swapfile
    for swapfile in /swapfile /swap /swap.img; do
      if [[ -f "$swapfile" ]]; then
        local size_mb
        size_mb="$(du -m "$swapfile" 2>/dev/null | awk '{print $1}')"
        rm -f "$swapfile"
        ok "已删除 swap 文件：$swapfile（释放 ${size_mb:-?} MB）"
      fi
    done

    # 注释 fstab 中的 swap 行
    if grep -qE '^[^#].*\bswap\b' /etc/fstab 2>/dev/null; then
      sed -i '/\bswap\b/s/^/#/' /etc/fstab
      ok "已注释 /etc/fstab 中的 swap 条目（重启后不会恢复）"
    fi

    # 设置 swappiness 为 0
    sysctl -w vm.swappiness=0 >/dev/null 2>&1
    # 永久写入
    if grep -q '^vm.swappiness' /etc/sysctl.conf 2>/dev/null; then
      sed -i '/^vm.swappiness/d' /etc/sysctl.conf
    fi
    echo "vm.swappiness=0" >> /etc/sysctl.conf

    ok "swappiness 已设为 0（已永久保存）"

    line
    local freed_mb=$((swap_total_kb / 1024))
    ok "Swap 优化完成，共释放约 ${freed_mb} MB 磁盘空间"

  elif [[ "$action" == "lower" ]]; then
    # ---- 降低 swappiness ----
    sysctl -w vm.swappiness=10 >/dev/null 2>&1
    sysctl -w vm.vfs_cache_pressure=50 >/dev/null 2>&1

    # 永久写入
    local param
    for param in "vm.swappiness=10" "vm.vfs_cache_pressure=50"; do
      local key="${param%%=*}"
      if grep -q "^${key}" /etc/sysctl.conf 2>/dev/null; then
        sed -i "/^${key}/d" /etc/sysctl.conf
      fi
      echo "$param" >> /etc/sysctl.conf
    done

    line
    ok "swappiness 已降至 10，vfs_cache_pressure 已降至 50（已永久保存）"
    info "Swap 仍保留作为安全缓冲，但内核将极少使用"
  fi
}

system_optimize_menu(){
  while true; do
  clear
  echo -e "${BOLD}【系统级深度优化菜单】${NC}"
  echo "1) 应用优化（临时生效，重启失效）"
  echo "2) 应用优化并设置开机自启 (rc.local)"
  echo "3) 还原默认配置"
  echo "4) 强制清除所有限速规则 (tc qdisc clean)"
  echo "5) 设置网卡发送队列长度 (txqueuelen)"
  echo "0) 返回主菜单"
  line
  read -rp "请输入选项: " choice
  case "$choice" in
    1) apply_system_optimizations; pause ;;
    2) apply_system_optimizations "persist"; pause ;;
    3) restore_system_optimizations; pause ;;
    4) clear_tc_rules; pause ;;
    5) set_txqueuelen; pause ;;
    0) return ;;
    *) warn "无效选择" ;;
  esac
  done
}

clear_tc_rules(){
  echo
  echo -e "${BOLD}【清除流量控制 (Traffic Control) 规则】${NC}"
  line
  
  local nic
  nic="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  [[ -z "$nic" ]] && nic="eth0"
  
  info "正在清除网卡 $nic 上的排队规则 (qdisc)..."
  tc qdisc del dev "$nic" root 2>/dev/null || true
  
  info "正在清除 iptables 可能的流量标记 (mangle 表)..."
  iptables -t mangle -F OUTPUT 2>/dev/null || true
  
  # 重新应用默认队列 fq
  info "重新应用默认队列 (fq)..."
  sysctl -w net.core.default_qdisc=fq >/dev/null 2>&1
  tc qdisc add dev "$nic" root fq 2>/dev/null || true
  
  echo
  ok "已清除所有限速/整形规则，并重置为 fq。"
  echo "注意：如果是 Throttle.sh 残留的 limit，现在已被移除。"
}

view_current_rules(){
  echo
  echo -e "${BOLD}【当前优化规则校验】${NC}"
  line
  
  # 获取并显示当前 Profile 名称
  local p_code p_desc
  if [[ -f "$PROFILE_STATE_FILE" ]]; then
    p_code="$(cat "$PROFILE_STATE_FILE" | tr -d ' \n\r')"
    p_desc="$(get_profile_name "$p_code")"
    echo "当前应用方案：${GREEN}${p_desc}${NC}"
  else
    echo "当前应用方案：${YELLOW}未知 (未检测到状态文件)${NC}"
  fi

  local config_file="$ACTIVE_FILE"
  if [[ ! -f "$config_file" ]]; then
    warn "未找到托管配置文件：$config_file"
    read -rp "是否查看 /etc/sysctl.conf ? [y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
       config_file="/etc/sysctl.conf"
    else
       return
    fi
  fi

  echo "配置文件路径：$config_file"
  printf "${BOLD}%-32s %-20s %-20s %s${NC}\n" "参数键 (Key)" "配置 (Conf)" "系统 (Sys)" "状态"
  line

  # 使用 awk 预处理：去重（最后写入生效）、去除注释空行
  # output format: key=value
  local effective_conf awk_src
  # Use read to load awk script into variable safe from quoting issues
  # || true is needed because read returns 1 when it hits EOF without delimiter
  read -r -d '' awk_src <<'AWK_EOF' || true
    BEGIN { FS="=" }
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    {
      # Normalize key: trim spaces
      key=$1; gsub(/^[ \t]+|[ \t]+$/, "", key)
      
      # Normalize val: trim spaces, remove inline comments
      val=$2; sub(/#.*/, "", val); gsub(/^[ \t]+|[ \t]+$/, "", val)
      
      if (key != "" && val != "") {
        conf[key] = val
        if (!(key in seen)) {
            keys[++k] = key
            seen[key] = 1
        }
      }
    }
    END {
      for (i=1; i<=k; i++){
        print keys[i] "=" conf[keys[i]]
      }
    }
AWK_EOF
  effective_conf="$(awk "$awk_src" "$config_file")"

  while IFS='=' read -r key val; do
    # Get system value
    local sys_val
    sys_val="$(sysctl -n "$key" 2>/dev/null || echo "MISSING")"
    
    # Normalize for comparison: collapse multiple spaces/tabs into single space
    local clean_val clean_sys
    clean_val="$(echo "$val" | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    clean_sys="$(echo "$sys_val" | tr '\t' ' ' | tr -s ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

    local status
    if [[ "$sys_val" == "MISSING" ]]; then
        status="${RED}MISSING${NC}"
    elif [[ "$clean_val" == "$clean_sys" ]]; then
        status="${GREEN}OK${NC}"
    else
        status="${YELLOW}DIFF${NC}"
    fi
    
    # Truncate values for display if too long
    local d_val="$val"
    local d_sys="$sys_val"
    if (( ${#d_val} > 20 )); then d_val="${d_val:0:18}.."; fi
    if (( ${#d_sys} > 20 )); then d_sys="${d_sys:0:18}.."; fi
    
    printf "%-32s %-20s %-20s %b\n" "$key" "$d_val" "$d_sys" "$status"

  done <<< "$effective_conf"
  line
  echo "注：DIFF 表示系统实际运行值与配置文件不一致 (忽略空白符差异)"
  pause
}

# ===================== 脚本更新 =====================
SCRIPT_PATH="/root/net-tune-pro-v3-zh.sh"

update_script(){
  echo
  echo -e "${BOLD}【脚本更新】${NC}"
  line
  info "当前版本：$VERSION"
  info "正在检查新版本..."

  local update_url="https://raw.githubusercontent.com/suxayii/Throttle/master/net-tune-pro-v3-zh.sh"
  local tmp_file="/tmp/net-tune-pro-update.sh"

  if cmd_exists curl; then
    curl -fsSL "$update_url" -o "$tmp_file"
  elif cmd_exists wget; then
    wget -qO "$tmp_file" "$update_url"
  else
    err "未找到 curl 或 wget，无法下载更新"
    return 1
  fi

  if [[ ! -s "$tmp_file" ]]; then
    err "下载失败或文件为空，请检查网络连接"
    rm -f "$tmp_file"
    return 1
  fi

  # 简单的内容比对
  if [[ -f "$SCRIPT_PATH" ]] && cmp -s "$SCRIPT_PATH" "$tmp_file"; then
    ok "当前已是最新版本"
    rm -f "$tmp_file"
    return 0
  else
    # 尝试提取新版本号（如果脚本里有定义 VERSION）
    local new_ver
    new_ver="$(grep '^VERSION=' "$tmp_file" | head -1 | cut -d'"' -f2 || true)"
    [[ -z "$new_ver" ]] && new_ver="未知"
    
    info "发现新版本：$new_ver"
    read -rp "是否更新脚本？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      install -m 0755 "$tmp_file" "$SCRIPT_PATH"
      rm -f "$tmp_file"
      ok "脚本已更新到 $SCRIPT_PATH，即将重新加载..."
      sleep 2
      exec bash "$SCRIPT_PATH"
    else
      info "已取消更新"
      rm -f "$tmp_file"
    fi
  fi
}

# ===================== 菜单 =====================
choose_profile_menu(){
  local p p_name
  while true; do
    clear
    echo -e "${BOLD}【选择并应用网络优化方案】${NC}"
    line
    echo "1) 平衡版（通用推荐）"
    echo "2) 激进版（高并发/高PPS）"
    echo "3) 激进稳妥版（推荐）"
    echo "4) UDP 专项版（s-ui Hysteria2 生产极致版）"
    echo "5) 流媒体代理版（VLESS/Reality TCP）"
    echo "6) HTTP 代理专项版（Squid/Nginx/Clash）"
    echo "7) 低内存保守版（1C/1G）"
    echo "8) 低内存保守版（2C/2G）"
    echo "9) 高带宽版（1G口）"
    echo "10) 高带宽版（10G口）"
    echo "11) VPS 极致带宽版（虚拟网卡）"
    echo "12) 晚高峰抗抖动版 (Anti-Bufferbloat) [推荐]"
    echo "0) 返回"
    line
    read -rp "请输入选项 [0-12]: " c

    case "$c" in
      1) p="balanced"; p_name="平衡版（通用推荐）" ;;
      2) p="aggressive"; p_name="激进版（高并发/高PPS）" ;;
      3) p="aggressive_safe"; p_name="激进稳妥版（推荐）" ;;
      4) p="udp_quic"; p_name="UDP 专项版（s-ui Hysteria2 生产极致版）" ;;
      5) p="streaming"; p_name="流媒体代理版（VLESS/Reality TCP）" ;;
      6) p="http_proxy"; p_name="HTTP 代理专项版（Squid/Nginx/Clash）" ;;
      7) p="low_1c1g"; p_name="低内存保守版（1C/1G）" ;;
      8) p="low_2c2g"; p_name="低内存保守版（2C/2G）" ;;
      9) p="bw_1g"; p_name="高带宽版（1G口）" ;;
      10) p="bw_10g"; p_name="高带宽版（10G口）" ;;
      11) p="vps_max"; p_name="VPS 极致带宽版（虚拟网卡）" ;;
      12) p="peak_jitter"; p_name="晚高峰抗抖动版 (Anti-Bufferbloat)" ;;
      0) return ;;
      *) warn "无效输入"; sleep 1; continue ;;
    esac

    precheck || { pause; continue; }
    conflict_check
    read -rp "确认应用「$p_name」吗？[y/N]: " yn
    if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
      apply_profile "$p" && ok "已应用：$p_name"
    else
      warn "已取消"
    fi
    pause
    return
  done
}
enable_bbr_fq(){
  echo
  echo -e "${BOLD}【一键开启 BBR + fq】${NC}"
  line
  
  if ! cmd_exists modprobe; then
    warn "未找到 modprobe，将尝试直接通过 sysctl 开启..."
  else
    if ! lsmod 2>/dev/null | grep -q bbr; then
      info "尝试加载 tcp_bbr 模块..."
      modprobe tcp_bbr 2>/dev/null || true
    fi
  fi

  local bbr_conf="/etc/sysctl.conf"
  info "正在配置系统主配置文件：$bbr_conf"

  # 清理可能存在的旧配置
  if [[ -f "$bbr_conf" ]]; then
    sed -i '/^net\.core\.default_qdisc/d' "$bbr_conf"
    sed -i '/^net\.ipv4\.tcp_congestion_control/d' "$bbr_conf"
  fi

  echo "net.core.default_qdisc = fq" >> "$bbr_conf"
  echo "net.ipv4.tcp_congestion_control = bbr" >> "$bbr_conf"

  sysctl -p "$bbr_conf" >/dev/null 2>&1 || true

  local current_cc current_qdisc
  current_cc="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  current_qdisc="$(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"

  if [[ "$current_cc" == "bbr" && "$current_qdisc" == "fq" ]]; then
      ok "BBR + fq 已成功开启！"
      info "配置已持久化保存至自带系统配置：$bbr_conf"
  else
      warn "开启失败或仅部分生效。当前拥塞控制：$current_cc，队列：$current_qdisc"
      warn "可能是内核版本过低（需要 4.9+）或存在不支持的虚拟化环境（如 OpenVZ）"
  fi
}

main_menu(){
  while true; do
    clear
    echo -e "${BOLD}${BLUE}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║   Net Tune Pro v3 中文版（网络优化全功能）             ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo "1) 预检查阶段"
    echo "2) 冲突检测（sysctl 重复键）"
    echo "3) 应用网络优化方案（原子写入）"
    echo "4) 查看当前状态"
    echo "5) 实时监控"
    echo "6) 回滚到上一次应用点"
    echo "7) 创建永久初始备份（仅首次）"
    echo "8) 回滚到永久初始配置（管理文件范围）"
    echo "9) 查看历史快照列表"
    echo "10) 清理旧快照（保留最近20个）"
    echo "11) 网卡/系统级深度优化 (Virtio/GRO)"
    echo "12) Swap 优化（关闭/降低 swappiness）"
    echo "13) 更新脚本"
    echo "14) 查看当前优化规则"
    echo "15) 智能检测与自动优化（硬件 + mtr 线路）"
    echo "16) 一键开启 BBR + fq (单项优化)"
    echo "0) 退出"
    line
    read -rp "请输入选项: " ch
    case "$ch" in
      1) precheck; pause ;;
      2) conflict_check; pause ;;
      3) choose_profile_menu ;;
      4) show_status; pause ;;
      5) watch_metrics ;;
      6) rollback_last_apply_point; pause ;;
      7) save_permanent_baseline; pause ;;
      8)
        read -rp "确认回滚到永久初始配置？[y/N]: " yn
        if [[ "${yn:-N}" =~ ^[Yy]$ ]]; then
          restore_permanent_baseline
        else
          warn "已取消"
        fi
        pause
        ;;
      9) ls -1 "$HISTORY_DIR" 2>/dev/null | sort || true; pause ;;
      10) clean_old_snapshots 20; pause ;;
      11) system_optimize_menu ;;
      12) optimize_swap; pause ;;
      13) update_script; pause ;;
      14) view_current_rules ;;
      15) auto_optimize; pause ;;
      16) enable_bbr_fq; pause ;;
      0) ok "已退出"; exit 0 ;;
      *) warn "无效输入"; sleep 1 ;;
    esac
  done
}

need_root
check_base_deps
main_menu
